# LLM AS A JUDGE

In [1]:
!pip install --no-deps xformers trl peft accelerate bitsandbytes -q      
!pip install torch sacrebleu "unbabel-comet>=2.2.0" bert-score evaluate tensorflow numpy nltk -q
!pip install git+https://github.com/google-research/bleurt.git -q

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 31.5/31.5 MB 52.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 375.8/375.8 kB 17.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 67.0/67.0 MB 25.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 51.8/51.8 kB 2.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.5/55.5 kB 2.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 4.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 2.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 5.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 31.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 13.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 1.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 84.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 104.1/104.1 kB 6.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 91.0/91.0 kB 4.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 101.4/101.4 kB 6.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.1/61.1 kB 3.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 4.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 193.6/193.6 kB 10.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 294.9/294.9 kB 16.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 529.7/529.7 kB 25.7 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-api-core 1.34.1 requires protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<4.0.0dev,>=3.19.5, but you have protobuf 4.25.8 which is incompatible.
cesium 0.12.4 requires numpy<3.0,>=2.0, but you have numpy 1.26.4 which is incompatible.
bigframes 1.42.0 requires rich<14,>=12.4.4, but you have rich 14.0.0 which is incompatible.
google-spark-connect 0.5.2 requires google-api-core>=2.19.1, but you have google-api-core 1.34.1 which is incompatible.
gcsfs 2025.3.2 requires fsspec==2025.3.2, but you have fsspec 2025.3.0 which is incompatible.
google-cloud-bigtable 2.30.0 requires google-api-core[grpc]<3.0.0,>=2.16.0, but you have google-api-core 1.34.1 which is incompatible.
google-cloud-storage 2.19.0 requires google-api-core<3.0.0dev,>=2.15.0, but you have google-api-core 1.34.1 which is incompatible.
pandas-gbq 0.28.0 requires google-api-core<3.0.0dev,>=2.10.2, but you have google-api-core 1.34.1 which is incompatible.
  Preparing metadata (setup.py) ... done
  Building wheel for BLEURT (setup.py) ... done

In [2]:
import torch, datetime, re
import pandas as pd
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig
import sacrebleu                                 
from sacrebleu.metrics import TER                 
from nltk.translate.meteor_score import single_meteor_score  
import numpy as np          
from typing import Union, Dict, List
import warnings

In [3]:
print("Loading Prometheus (4‑bit) …")
bnb_cfg = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_use_double_quant=True,
    bnb_4bit_compute_dtype=torch.bfloat16,
)

model = AutoModelForCausalLM.from_pretrained(
    "Unbabel/M-Prometheus-7B",
    quantization_config=bnb_cfg,
    device_map="auto",
    trust_remote_code=True,
)

tokenizer = AutoTokenizer.from_pretrained(
    "Unbabel/M-Prometheus-7B",
    trust_remote_code=True,
)

model.eval()

Loading Prometheus (4‑bit) …

config.json:   0%|          | 0.00/790 [00:00<?, ?B/s]

2025-06-23 00:43:53.272391: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1750639433.511584      19 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1750639433.578163      19 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered

model.safetensors.index.json:   0%|          | 0.00/27.8k [00:00<?, ?B/s]

Fetching 4 files:   0%|          | 0/4 [00:00<?, ?it/s]

model-00004-of-00004.safetensors:   0%|          | 0.00/1.09G [00:00<?, ?B/s]

model-00001-of-00004.safetensors:   0%|          | 0.00/4.88G [00:00<?, ?B/s]

model-00002-of-00004.safetensors:   0%|          | 0.00/4.93G [00:00<?, ?B/s]

model-00003-of-00004.safetensors:   0%|          | 0.00/4.33G [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/243 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/7.31k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/2.78M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/1.67M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/11.4M [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/605 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/613 [00:00<?, ?B/s]

Qwen2ForCausalLM(
  (model): Qwen2Model(
    (embed_tokens): Embedding(152064, 3584, padding_idx=151643)
    (layers): ModuleList(
      (0-27): 28 x Qwen2DecoderLayer(
        (self_attn): Qwen2Attention(
          (q_proj): Linear4bit(in_features=3584, out_features=3584, bias=True)
          (k_proj): Linear4bit(in_features=3584, out_features=512, bias=True)
          (v_proj): Linear4bit(in_features=3584, out_features=512, bias=True)
          (o_proj): Linear4bit(in_features=3584, out_features=3584, bias=False)
        )
        (mlp): Qwen2MLP(
          (gate_proj): Linear4bit(in_features=3584, out_features=18944, bias=False)
          (up_proj): Linear4bit(in_features=3584, out_features=18944, bias=False)
          (down_proj): Linear4bit(in_features=18944, out_features=3584, bias=False)
          (act_fn): SiLU()
        )
        (input_layernorm): Qwen2RMSNorm((3584,), eps=1e-06)
        (post_attention_layernorm): Qwen2RMSNorm((3584,), eps=1e-06)
      )
    )
    (norm): Qwen2RMSNorm((3584,), eps=1e-06)
    (rotary_emb): Qwen2RotaryEmbedding()
  )
  (lm_head): Linear(in_features=3584, out_features=152064, bias=False)
)

In [4]:
templates = {
        "general":'''###Task Description:
An instruction, a response to evaluate, a **gold translation** (reference answer) and a score rubric representing an evaluation criterion are given.

1. Write a detailed feedback of maximum 100 words that assesses the response strictly according to the score rubric (translation quality), **not evaluating in general**.
2. After writing the feedback, write a score that is an integer between 1 and 5. You must refer to the rubric.
3. The output format must be EXACTLY:
"<your feedback here>
[RESULT] <integer 1-5>"
4. Do not generate any headers, closings, or extra commentary.

###The instruction to evaluate:
Traduci il seguente brano di italiano arcaico nel moderno italiano:
«{ARCHAIC_PASSAGE}»

###Response to evaluate (model output):
{MODEL_TRANSLATION}

###Gold Translation (reference answer):
{GOLD_TRANSLATION}

###Score Rubric (Translation Quality):
5 – Excellent: The translation is fluid, precise, and natural. It preserves all the semantic nuances of the original text. The syntax is modern yet respectful of the source content. The text is perfectly readable and does not feel machine‑generated. Archaic terms are rendered with accurate modern equivalents, even in ambiguous cases. Indistinguishable from a translation by a highly qualified human.
4 – Good: A generally correct and readable translation. The text appears modern and understandable, although some expressions come across as slightly mechanical or overly literal. It preserves the overall meaning well but may lose subtle cultural or historical nuances. Some terms are adapted with a good but not optimal choice. It may resemble a solid human translation, but not an outstanding one.
3 – Sufficient: An understandable translation but with evident mechanical traits or stylistically poor passages. There may be rigid constructions, syntactic calques, or unnatural lexical choices. The global meaning is retained, but the expressive richness of the original medieval text is lost. It reads like an automatic translation with minimal human supervision.
2 – Insufficient: A discontinuous or incoherent translation. Sentences are disconnected, modern vocabulary is misused, and ambiguous or obsolete words are misinterpreted. Some passages are incomprehensible or misleading. It clearly feels like a text translated automatically without human intervention. Not reliable for reading or academic study.
1 – Gravely Insufficient: A failed translation. Sentences are nonsensical, terms are mistranslated or omitted entirely. There is no grammatical or semantic coherence. The text is unusable and devoid of communicative value. Neither the original content nor its purpose can be discerned. It seems produced by a crude or faulty automatic system, utterly lacking linguistic or historical understanding.

###Feedback:''',
        "grammatic":'''###Task Description:
An instruction, a model response, a gold translation (reference answer) and a score rubric for grammatical accuracy are provided.

1. Write detailed feedback of no more than 100 words that evaluates the response only against the grammatical rubric (morphology, syntax, agreement, punctuation, orthography). Do not comment on meaning or style.
2. After the feedback, give a score—an integer from 1 to 5—clearly tied to the rubric.
3. The output format must be EXACTLY:
"<your feedback here>
[RESULT] <integer 1-5>"
4. Do not generate headers, closings, or extra commentary.

###The instruction to evaluate:
Traduci il seguente brano di italiano arcaico nel moderno italiano:
«{ARCHAIC_PASSAGE}»

###Response to evaluate (model output):
{MODEL_TRANSLATION}

###Gold Translation (reference answer):
{GOLD_TRANSLATION}

###Score Rubric (Grammatic Quality):
5 – Flawless: Grammar, punctuation, and orthography are impeccable. Sentences flow naturally, with varied structure and perfect agreement of tense, number, and gender. Word order feels idiomatic and clear.
4 – Very Good: Only rare, minor slips (e.g., a missing comma or slight tense inconsistency). Fluency and correctness remain high; errors do not interrupt reading.
3 – Adequate: Noticeable but non-disruptive issues such as awkward word order, repeated structures, or several punctuation glitches. Readable but needs copy-editing.
2 – Poor: Frequent grammatical errors (agreement mistakes, run-ons, fragments) distract and sometimes blur meaning. Substantial revision required.
1 – Unacceptable: Pervasive, severe faults make the text hard to follow. Basic syntactic rules are ignored; comprehension is unreliable.

###Feedback:''',
        "semantic":'''###Task Description:
An instruction, a model response, a gold translation (reference answer) and a score rubric for semantic accuracy are provided.

1.Write detailed feedback of no more than 100 words that evaluates the response only against the semantic rubric (fidelity of meaning, preservation of nuance, contextual appropriateness). Do not comment on grammar or style.
2.After the feedback, give a score—an integer from 1 to 5—clearly tied to the rubric.
3.The output format must be EXACTLY:
"<your feedback here>
[RESULT] <integer 1-5>"
4.Do not generate headers, closings, or extra commentary.

###The instruction to evaluate:
Traduci il seguente brano di italiano arcaico nel moderno italiano:
«{ARCHAIC_PASSAGE}»

###Response to evaluate (model output):
{MODEL_TRANSLATION}

###Gold Translation (reference answer):
{GOLD_TRANSLATION}

###Score Rubric (Semantic Quality):
5 – Excellent: All intended meanings, nuances, and relationships are conveyed with precision. Concepts are accurately represented, contextually appropriate, and internally consistent. No misinterpretations or omissions; the text mirrors the source’s full informational depth.
4 – Good: The core meaning and almost all subtleties are preserved. A few minor shades of sense or cultural references may be softened, but factual content and logical relations remain intact. Overall message fidelity is high.
3 – Sufficient: Central ideas are captured, yet several nuances, implications, or culturally loaded elements are diluted or missed. Some statements may feel slightly out of context, but the general message survives without critical distortion.
2 – Insufficient: Major semantic inaccuracies, omissions, or additions alter the author’s intent. Key concepts are confused or simplified, leading to a partial or skewed understanding of the original content.
1 – Gravely Insufficient: Meaning is largely lost or contradicted. Essential ideas are misrepresented, context is ignored, and the text may introduce content not present in the source. Readers cannot rely on the translation to grasp the original message.

###Feedback:'''}
def judge(to_predict, prediction, gold, mode, verbose=0):
    if mode not in set(templates.keys()): raise ValueError("unaccepeted mode")
    
    prompt = templates[mode].format(
        ARCHAIC_PASSAGE=to_predict.strip(),
        MODEL_TRANSLATION=prediction.strip(),
        GOLD_TRANSLATION=gold.strip()
    )

    # 2️⃣  Run Prometheus 2 --------------------------
    inputs = tokenizer(prompt, return_tensors="pt").to(model.device)
    lunghezza_input = len(inputs[0])
    if verbose>0:
        print(f"ORIGINAL:\n {to_predict}")
        print(f"PREDICTION:\n{prediction} ")
        print(f"GOLD:\n {gold}")
        print("▶ Generating judgement ...")
        t0 = datetime.datetime.now()

    with torch.no_grad():
        out = model.generate(**inputs, max_new_tokens= 256, do_sample=False)

    raw = tokenizer.decode(out[0][lunghezza_input:], skip_special_tokens=True)
    

    if verbose>1:
        print("RAW OUTPUT OF PROMETHEUS:")
        print(raw)
        print("END RAW")

    # 3️⃣  Parse feedback + numeric score ------------
    m = re.search(
        r"^(.*?)\s*\[RESULT\]\s*([1-5])\b",   # ① feedback   ② score
        raw,
        re.S                                   # dot matches newlines
    )
    if not m:
        print("!!!!!!  ERROR: Cannot parse Prometheus output:\n" + raw)
        print(f"Skipping the decomposition of judjment of the sentence: {prediction}")
        feedback = raw
        score    = raw
    else:
        feedback = m.group(1).strip()
        score    = int(m.group(2))
        if verbose>0:
            print(f"SCORE: {score}")
            print("")
        if verbose>1:
            print(f"FEEDBACK: {feedback}")
            print("⏱", datetime.datetime.now() - t0)

    return {"feedback": feedback, "score": score, "raw": raw}

In [5]:
# This is a small trick to avoid reloading models on repeated calls in the same script.
_MODEL_CACHE = {}

def evaluate_metrics(
    original: Union[str, List[str]],
    gold: Union[str, List[str]],
    predicted: Union[str, List[str]]
) -> Union[Dict[str, float], Dict[str, Dict]]:
    """
    A simple, all-in-one function to evaluate MT metrics.

    Handles both single sentences (str) and corpora (List[str]).
    It is resilient to failures in individual metric calculations.

    - For a single sentence, returns a flat dictionary of scores.
    - For a corpus, returns a dictionary where sentence-level metrics
      (BERTScore, BLEURT, COMET-22) contain a 'scores' list with a
      score for each sentence.
    """
    is_corpus = isinstance(gold, list)

    # --- 1. Standardize inputs to lists for uniform processing ---
    if not is_corpus:
        originals, golds, predicteds = [original], [gold], [predicted]
    else:
        if not (isinstance(original, list) and isinstance(predicted, list)):
            raise ValueError("If one input is a list (corpus), all must be lists.")
        originals, golds, predicteds = original, gold, predicted
    
    results = {}
    device = "cuda:0" if torch.cuda.is_available() else "cpu"
    print(f"Running evaluation on {len(golds)} sentence(s) using device: {device}")

    # --- 2. Sacrebleu-based Metrics (fast and reliable) ---
    results['BLEU'] = sacrebleu.corpus_bleu(predicteds, [golds]).score / 100
    results['chrF++'] = sacrebleu.corpus_chrf(predicteds, [golds], word_order=2).score / 100
    ter_score = sacrebleu.corpus_ter(predicteds, [golds]).score / 100
    results['TER (inv)'] = 1.0 - ter_score

    # --- 3. Model-based Metrics (slower, wrapped for safety) ---
    
    # BERTScore
    try:
        if 'bert_scorer' not in _MODEL_CACHE:
            print("Loading BERTScore model...")
            from bert_score import BERTScorer
            _MODEL_CACHE['bert_scorer'] = BERTScorer(lang="it", model_type='bert-base-multilingual-cased', device=device)
        _, _, F1 = _MODEL_CACHE['bert_scorer'].score(predicteds, golds, batch_size=2)
        results['BERTScore'] = F1.tolist() # <-- CHANGED: Store the list of scores
    except Exception as e:
        warnings.warn(f"Could not calculate BERTScore: {e}")
        results['BERTScore'] = [-1.0] * len(golds)

    # BLEURT
    try:
        if 'bleurt_scorer' not in _MODEL_CACHE:
            print("Loading BLEURT-20 model...")
            from evaluate import load as hf_load
            _MODEL_CACHE['bleurt_scorer'] = hf_load("bleurt", "BLEURT-20", module_type="metric")
        bleurt_scores = _MODEL_CACHE['bleurt_scorer'].compute(predictions=predicteds, references=golds)['scores']
        results['BLEURT'] = bleurt_scores # <-- CHANGED: Store the list of scores
    except Exception as e:
        warnings.warn(f"Could not calculate BLEURT. Error: {e}")
        results['BLEURT'] = [-1.0] * len(golds)

    # COMET
    try:
        if 'comet_model' not in _MODEL_CACHE:
            print("Loading COMET-22 model...")
            import comet
            model_path = comet.download_model("Unbabel/wmt22-comet-da")
            _MODEL_CACHE['comet_model'] = comet.load_from_checkpoint(model_path)
        comet_data = [{"src": s, "mt": p, "ref": r} for s, p, r in zip(originals, predicteds, golds)]
        comet_output = _MODEL_CACHE['comet_model'].predict(comet_data, batch_size=2, gpus=1, progress_bar=False)
        results['COMET-22'] = comet_output.scores # <-- CHANGED: Store the list of scores
    except Exception as e:
        warnings.warn(f"Could not calculate COMET-22. Error: {e}")
        results['COMET-22'] = [-1.0] * len(golds)

    # --- 4. Format Output ---
    if not is_corpus:
        # For a single sentence, extract the single score from the list
        return {
            'BLEU': round(results['BLEU'], 4),
            'chrF++': round(results['chrF++'], 4),
            'TER (inv)': round(results['TER (inv)'], 4),
            'BERTScore': round(results['BERTScore'][0], 4),
            'BLEURT': round(results['BLEURT'][0], 4),
            'COMET-22': round(results['COMET-22'][0], 4),
        }
    else:
        # For a corpus, return corpus scores and lists of sentence scores
        return {
            'BLEU': {'corpus_score': round(results.get('BLEU', -1), 4)},
            'chrF++': {'corpus_score': round(results.get('chrF++', -1), 4)},
            'TER (inv)': {'corpus_score': round(results.get('TER (inv)', -1), 4)},
            'BERTScore': {'scores': [round(s, 4) for s in results.get('BERTScore', [])]},
            'BLEURT': {'scores': [round(s, 4) for s in results.get('BLEURT', [])]},
            'COMET-22': {'scores': [round(s, 4) for s in results.get('COMET-22', [])]},
        }

In [6]:
# read the dataset with the llm traslations


translated_dataset = pd.read_csv("/kaggle/input/popuss/predicted_opus.csv")

In [7]:
import os
import pandas as pd

file_paths = [
    "/kaggle/input/predicted/predicted_mistral.xlsx",
    "/kaggle/input/predicted/predicted_opus.csv"
]
modes = ["grammatic", "semantic"]
for mode in modes:
    for path in file_paths:
        if path.endswith(".xlsx"):
            translated_dataset = pd.read_excel(path)
            translated_dataset = translated_dataset.rename(columns={"Mistral Traslation":"prediction"})
        elif path.endswith(".csv"):
            translated_dataset = pd.read_csv(path)
        else:
            raise ValueError(f"Unsupported file type: {path}")
        translated_dataset = translated_dataset
        # Judging
        scores = []
        feedbacks = []
        print(f"\n\nJudging {path}, {mode}\n\n")
        for idx, row in translated_dataset.iterrows():
            to_predict = row["Sentence"]
            gold      = row["TRADUZIONE ITALIANA"]
            prediction = row["prediction"]
    
            judgement = judge(
                to_predict,
                prediction,
                gold,
                mode=mode,
                verbose=1
            )
            scores.append(judgement["score"])
            feedbacks.append(judgement["feedback"])
        
        # e.g. inspect or save
        mt_metrics = evaluate_metrics(
            translated_dataset["Sentence"].to_list(),
            translated_dataset["TRADUZIONE ITALIANA"].to_list(),
            translated_dataset["prediction"].to_list()
        )
        translated_dataset['Score']    = scores
        translated_dataset['Feedback'] = feedbacks
        translated_dataset['BERTScore'] = mt_metrics['BERTScore']['scores']
        translated_dataset['COMET-22']  = mt_metrics['COMET-22']['scores']
        translated_dataset['BLEURT']    = mt_metrics['BLEURT']['scores']
        translated_dataset['BLEU']      = pd.Series(mt_metrics['BLEU']['corpus_score'], index=translated_dataset.index[[0]])
        translated_dataset['chrF++']    = pd.Series(mt_metrics['chrF++']['corpus_score'], index=translated_dataset.index[[0]])
        translated_dataset['TER (inv)']= pd.Series(mt_metrics['TER (inv)']['corpus_score'], index=translated_dataset.index[[0]])
    
        # --- DYNAMIC OUTPUT PATH ---
        base = os.path.splitext(os.path.basename(path))[0]              # e.g. "predicted_mistral"
        output_path = f"/kaggle/working/{base}_traduzioni_con_score_{mode}.xlsx"  # e.g. "predicted_mistral_traduzioni_con_score.xlsx"
        translated_dataset.to_excel(output_path, index=False)
    
        print(f"\nResults for {path} (saved to {output_path}):")
        print(translated_dataset[["Sentence", "prediction", "Score"]].head())
        print("\n\n\n\n\n\n")

Judging /kaggle/input/predicted/predicted_mistral.xlsx, grammatic


ORIGINAL:
 quella guerra ben fatta l' opera perché etc. Et dall' altra parte Aiaces era uno cavaliere franco e prode all' arme, di gran guisa, ma non era pieno di grande senno
PREDICTION:
Quella guerra fu condotta con grande abilità, ecc. Dall'altra parte, Aiace era un cavaliere coraggioso e abile nella guerra, di grande aspetto, ma non era pieno di grande senno.
GOLD:
 Quella guerra era ben condotta per l’impresa, eccetera. E d’altra parte Aiace era un cavaliere valoroso e audace in battaglia, di grande forza, ma non era dotato di grande saggezza
▶ Generating judgement ...

/usr/local/lib/python3.11/dist-packages/transformers/generation/configuration_utils.py:631: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.7` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/transformers/generation/configuration_utils.py:636: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.8` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/transformers/generation/configuration_utils.py:653: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `20` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

SCORE: 4

ORIGINAL:
 crudele, e di tutte le colpe pigli vendetta, come dice la legge, ed a neuno cavaliere perdoni che pecchi.
PREDICTION:
crudele, e di tutte le colpe prendi vendetta, come dice la legge, e non perdonare a nessun cavaliere che pecchi.
GOLD:
 Crudele, e si vendica di tutte le colpe, come prescrive la legge, e non perdona nessun cavaliere che sbagli
▶ Generating judgement ...
SCORE: 4

ORIGINAL:
 Non d' altra forza d' animo fue ornato Ponzio Aufidiano, romano cavaliere.
PREDICTION:
Non fu ornato di altro coraggio che Ponzio Aufidiano, cavaliere romano.
GOLD:
 Ponzio Aufidiano, cavaliere romano, non fu dotato di minore forza d’animo.
▶ Generating judgement ...
SCORE: 4

ORIGINAL:
 Se questo piace a tutti e se 'l tempo hae bisogno d'avere Pompeio per cavaliere e non per compagno, non riterrò più i fati.
PREDICTION:
Se questo piace a tutti e se il tempo richiede che Pompeo sia il cavaliere e non il compagno, non mi opporrò più al fato.
GOLD:
 Se questa è la volontà comune, e le circostanze richiedono Pompeo come guida piuttosto che come pari, allora non mi opporrò più al destino
▶ Generating judgement ...
SCORE: 4

ORIGINAL:
 Officio di questa arte pare che sia dicere appostatamente per fare credere, fine è far credere per lo dire.
PREDICTION:
Sembra che il compito di questa arte sia quello di dire appositamente le cose per farle credere, il fine è convincere con le parole.
GOLD:
 Il compito di quest’arte sembra essere il parlare in modo appropriato per convincere; il suo fine è far credere attraverso il discorso.
▶ Generating judgement ...
SCORE: 4

ORIGINAL:
 Ecco e larghi ventipiovoli caggiono delle risolute nebbie; e potresti credere che tutto il cielo cadesse nel mare
PREDICTION:
Ecco, come grandi gocce di pioggia cadono dalle risolute nebbie; e potresti giurare che tutto il cielo stia crollando nel mare.
GOLD:
 Ecco, larghi scrosci di pioggia cadono dalle nebbie dissolte; e potresti credere che tutto il cielo stia precipitando nel mare
▶ Generating judgement ...
SCORE: 4

ORIGINAL:
 Però che or chi spererebbe quello che eziandio questi che non vogliono ancora credere in Cristo, già veggiono con noi, e perché nol possono negare, stridono colli denti.
PREDICTION:
Perciò, chi ora spererebbe che anche coloro che ancora non vogliono credere in Cristo, vedano con noi, e poiché non possono negarlo, siano costretti a serrare i denti.
GOLD:
 Chi potrebbe dunque sperare ciò che anche coloro che ancora non vogliono credere in Cristo già vedono insieme a noi, e poiché non possono negarlo, digrignano i denti?
▶ Generating judgement ...
SCORE: 4

ORIGINAL:
 I vendimenti de' morti et le presure de' vivi fece la frode d'uno feroce re.
PREDICTION:
Le spoglie dei morti e le pretese dei vivi furono la frode di un re feroce.
GOLD:
 La frode di un re feroce causò la vendita dei beni dei morti e le pressioni sui vivi.
▶ Generating judgement ...
SCORE: 4

ORIGINAL:
 Acciocché quegli, il quale ora per le sue gran reità è feroce e onorevole, egli d'ogni male afflitto e tormentato della impietà verso il mio padre.
PREDICTION:
Affinché colui, che ora per le sue grandi imprese è feroce e onorevole, soffra e sia tormentato da ogni male a causa della sua impietà verso mio padre.
GOLD:
 Affinché colui che ora, per le sue grandi colpe, è feroce e rispettato, sia afflitto e tormentato da ogni male a causa della sua empietà verso mio padre."
▶ Generating judgement ...
SCORE: 4

ORIGINAL:
 Gli uomini spessamente a stare fermi nella bugia incontra la verità.
PREDICTION:
Gli uomini spesso incontrano la verità stando fermi nella bugia.
GOLD:
 Gli uomini spesso, rimanendo fermi nella menzogna, incontrano la verità
▶ Generating judgement ...
SCORE: 5

ORIGINAL:
 Marco Cornelio ch'era de' dieci compagni, studiosamente  si riservò di parlare all'ultimo.
PREDICTION:
Marco Cornelio, che era uno dei dieci compagni, si riservò di parlare per ultimo, con attenzione.
GOLD:
 Marco Cornelio, che faceva parte dei dieci compagni, con attenzione e prudenza si tenne per ultimo nel parlare
▶ Generating judgement ...
SCORE: 4

ORIGINAL:
 cose ch'io sapeva che erano fatte in Italia.
PREDICTION:
cose che sapevo essere fatte in Italia.
GOLD:
 Cose che io sapevo essere state fatte in Italia
▶ Generating judgement ...
SCORE: 2

ORIGINAL:
 Corbio nipote d' Ortensio menò sua vita più bassa e più viziosa
PREDICTION:
Corbio, nipote di Ortensio, condusse una vita più bassa e più viziosa.
GOLD:
 Corbio, nipote di Ortensio, condusse una vita più bassa e più viziosa
▶ Generating judgement ...
SCORE: 5

ORIGINAL:
 Altressì uno amante chiamando merzé alla sua donna dice parole e ragioni molte, et ella si difende in suo dire.
PREDICTION:
Allo stesso modo, un amante chiamando misericordia dalla sua donna dice parole e ragioni tante, e lei si difende in quello che dice.
GOLD:
 Allo stesso modo, un amante chiamando merzé (rimprovero) alla sua donna dice molte parole e ragioni, e lei si difende nel suo discorso
▶ Generating judgement ...
SCORE: 4

ORIGINAL:
 Io mi ricordo (ch. 347) che essendo adirato scapigliai la mia donna. Ohi, quanti dì questa ira mi tolse!
PREDICTION:
Mi ricordo (c. 347) che, essendo arrabbiato, le sbarrai la strada con la mia donna. Ohimè, quante giornate mi ha fatto passare questa rabbia!
GOLD:
 Ricordo che, essendo arrabbiato, misi in disordine i capelli della mia donna. Oh, quanti giorni questa collera mi tolse
▶ Generating judgement ...
SCORE: 1

ORIGINAL:
 colui del quale tu tti solevi dolere ch' era amante della tua donna;
PREDICTION:
colui del quale tu eri solita lamentarti, era l'amante della tua donna.
GOLD:
 Colui del quale tu eri solito dolerti perché era amante della tua donna
▶ Generating judgement ...
SCORE: 4

ORIGINAL:
 Ma no sapeano già le nomora di coloro dela congiurazione, ché la donna no nominava già li nomi.
PREDICTION:
Ma non sapevano ancora i nomi di coloro della congiura, poiché la donna non aveva ancora menzionato i nomi.
GOLD:
 Ma non conoscevano ancora i nomi di coloro della congiura, perché la donna non aveva ancora nominato i nomi
▶ Generating judgement ...
SCORE: 4

ORIGINAL:
 Creti?  Certo quand'elli si mosse, elli ti dixe: "O fedele mia donna, fa' che in mio luogo ti sia racomandato il nostro hoste troiano".
PREDICTION:
Creti? Certo, quando lui si mosse, lui ti disse: "Oh mia fedele donna, assicurati che il nostro ospite troiano sia raccomandato al mio posto".
GOLD:
 Creti? Certo, quando lui si mosse, ti disse: 'O mia fedele donna, fa’ che sia raccomandato a te, al mio posto, il nostro ospite troiano
▶ Generating judgement ...
SCORE: 4

ORIGINAL:
 A Milano fue ripressa la malvagità d' una donna in simile bugìa, nel tempo medesimo di questo signore della republica, in questo modo:
PREDICTION:
A Milano fu repressa la malvagità di una donna che mentiva, nello stesso periodo di questo signore della repubblica, in questo modo:
GOLD:
 A Milano fu scoperta la malvagità di una donna in una simile menzogna, nel medesimo tempo di questo signore della repubblica, in questo modo
▶ Generating judgement ...
SCORE: 4

ORIGINAL:
 E lamentavansi dell'iniquità d'Appio, e ripiagnevano la malavventurata beltà della pulcella e la necessità del padre.
PREDICTION:
Si lamentavano dell'ingiustizia di Appio e piangevano per la sventurata bellezza della fanciulla e per la necessità del padre.
GOLD:
 Si lamentavano dell’ingiustizia di Appio, e piangevano per la sfortunata bellezza della ragazza e per la necessità del padre
▶ Generating judgement ...
SCORE: 4

ORIGINAL:
 Nella quale battaglia, certo io ebbi sempre ardire di ragionare di pace e sempre mi dolfi che non solamente la pace era schifata,
PREDICTION:
In tale battaglia, io mi sono sempre adoperato per parlare di pace e ho sempre pensato che non solo la pace fosse disprezzata,
GOLD:
 In quella battaglia, certamente ebbi sempre il coraggio di parlare di pace, e mi dolevo che non solo la pace fosse disprezzata
▶ Generating judgement ...
SCORE: 4

ORIGINAL:
 la seconda suole talora per la grande provedenzia fare timoroso, e la prima per l'ardire rendere altrui matto.
PREDICTION:
Il secondo [evento] a volte fa temere per la grande provenienza, e il primo per ardire rende l'altro pazzo.
GOLD:
 La seconda talvolta, a causa della grande prudenza, rende timoroso, e la prima , per l’audacia, fa diventare pazzo qualcun altro
▶ Generating judgement ...
SCORE: 4

ORIGINAL:
 Andò nel campo de' Cartaginesi e tutta la legione trasse seco.
PREDICTION:
Andò nel campo dei Cartaginesi e portò con sé tutta la legione.
GOLD:
 Entrò nel campo dei Cartaginesi e condusse con sé tutta la legione
▶ Generating judgement ...
SCORE: 4

ORIGINAL:
 Non lo volle cognoscere per nimico. Qesta è quella, la quale diede ardire al profeta Natan a riprendere con grande autoritade quello re, il quale avea peccato.
PREDICTION:
Non voleva riconoscerlo come nemico. Questa è lei, la donna che diede il coraggio al profeta Nathan di rimproverare con grande autorevolezza il re, che aveva peccato.
GOLD:
 Non lo volle riconoscere come nemico. Questa è colei che diede coraggio al profeta Natan a riprendere con grande autorità quel re che aveva peccato
▶ Generating judgement ...
SCORE: 4

ORIGINAL:
 l'armi et insieme con loro passaseno tra li nimici, perçò se alcuno non avesse ardire de questo et sì avevano questo animo.
PREDICTION:
E con loro passavano le armi, perciò se qualcuno non avesse avuto il coraggio di fare questo, e così era nel loro animo.
GOLD:
 Le armi e insieme con esse passarono tra i nemici, perciò se qualcuno non avesse avuto coraggio in ciò, non avrebbe avuto questo spirito
▶ Generating judgement ...
SCORE: 4

ORIGINAL:
 Unde ragionevolemente Iob è interpretato dolente;
PREDICTION:
Per questo motivo, Giobbe viene interpretato come sofferente.
GOLD:
 Per questo, ragionevolmente, Giobbe è interpretato come dolente
▶ Generating judgement ...
SCORE: 4

ORIGINAL:
 quello che sopra tutti gli altri perdonasse a' cittadini, e a cui più sicuramente possiate credere; poi ch'egli fu vostro comandatore.
PREDICTION:
colui che perdonò più di tutti agli altri ai cittadini, e a cui potete credere più sicuramente; poiché egli era il vostro comandante.
GOLD:
 Colui che perdonava più di tutti gli altri i cittadini, e a cui potete credere con maggior sicurezza; poiché egli fu vostro comandante
▶ Generating judgement ...
SCORE: 4

ORIGINAL:
 in vano si domanda chi questo Libro scrivesse, con ciò sia cosa che fedelmente si debba credere che l'Auttore di quello fusse lo Spirito santo.
PREDICTION:
Inutilmente si chiede chi abbia scritto questo Libro, dato che è una verità che fedelmente si deve credere che l'Autore sia lo Spirito Santo.
GOLD:
 Invano si domanda chi abbia scritto questo Libro, poiché si deve credere fedelmente che l’Autore di esso sia lo Spirito Santo.
▶ Generating judgement ...
SCORE: 4

ORIGINAL:
 se non fosse usatissima, ciò parrebbe certo molto più incredibile: certo più agevolmente si può credere quello, posto che l'umano spirito al divino, ed il mutabile allo incommutabile
PREDICTION:
se non fosse una frase così comune, suonerebbe certamente come qualcosa di incredibile: è molto più facile credere che l'umano possa assomigliare al divino, e il mutevole all'immutabile.
GOLD:
 Se non fosse così frequentemente usata, questa cosa sembrerebbe certamente molto più incredibile; invece è più facile credere a ciò, dato che lo spirito umano si riferisce a quello divino, e ciò che è mutevole a ciò che è incorruttibile
▶ Generating judgement ...
SCORE: 2

ORIGINAL:
 che prendessero la paga dal camarlingo per loro dispensa et immantenente andassero alla presenzia di messer lo papa per contradiare il passamento de' cavalieri che veniano di Cecilia in Toscana
PREDICTION:
he prendessero la paga dal tesoriere per la loro spesa e immediatamente andassero da mastro il papa per contraddire il passaggio dei cavalieri che venivano da Cecilia in Toscana.
GOLD:
 Che prendessero la paga dal camerlingo per la loro dispensa e immediatamente andassero alla presenza di messer il papa per ostacolare il passaggio dei cavalieri che venivano da Cecilia in Toscana.
▶ Generating judgement ...
SCORE: 2

ORIGINAL:
 Teseo reguardò Achelao fortemente meravigliandose e disse così: "O messer Achelao, io vi prego che voi me diciate in che modo voi perdeste
PREDICTION:
Teseo lo guardò Achelao con stupore e disse: "Oh signor Achelao, vi prego, dimmi come hai perso"
GOLD:
 Teseo guardò Achelao con grande stupore e disse: 'O messer Achelao, vi prego di dirmi come avete perso
▶ Generating judgement ...
SCORE: 4

ORIGINAL:
 Io spero in messer Iesù di mandare tosto a voi Timoteo, acciocché io sia d'animo buono
PREDICTION:
Spero in messer Gesù di mandarti presto Timoteo, per tranquillizzare la mia mente.
GOLD:
 Spero in messer Gesù di mandare presto a voi Timoteo, affinché io possa avere buon animo
▶ Generating judgement ...
SCORE: 5

ORIGINAL:
 sanza fallo lo porco salvatico avanza l' uomo d' udire e 'l lupo cerviere del vedere
PREDICTION:
senza dubbio il selvatico porco avanza l'uomo nell'ascolto e il lupo nel vedere.
GOLD:
 Senza dubbio il cinghiale selvatico supera l’uomo nell’udito e il lupo nel vedere
▶ Generating judgement ...
SCORE: 5

ORIGINAL:
 uno luogo si mandano lancioni;  la quale cosa i cavalieri l' appellano capo di porco
PREDICTION:
un luogo dove si mandano lance; la quale cosa i cavalieri chiamano "testa di maiale"
GOLD:
 In un punto si inviano lance; questa manovra i cavalieri la chiamano 'capo di porco'
▶ Generating judgement ...
SCORE: 4

ORIGINAL:
 tenda le reti a li cerbi e sa bene in quali valle dimori il furioso porco cinghiare.
PREDICTION:
tenda le reti ai cervi e sa bene in quale valle dimori il selvaggio maiale incorni.
GOLD:
 Tende le reti per i cerbiatti e conosce bene in quali valli dimora il feroce cinghiale
▶ Generating judgement ...
SCORE: 4

ORIGINAL:
 Ora spaventerai li disidirosi cervi con varie e diverse paure, o lo porco cenghiare caggia in terra passato collo spiedo.
PREDICTION:
Ora spaventerai i cervi disidratati con varie e diverse paure, o il maiale selvatico cadrà a terra trafitto dallo spiedo.
GOLD:
 Ora spaventerai i cervi timorosi con varie e molte paure, o il cinghiale cadrà a terra infilzato dallo spiedo
▶ Generating judgement ...
SCORE: 4

ORIGINAL:
 tratta la natura delle cose incorporali le quali non conversano intra lle corpora, sì come Dio e le divine cose.
PREDICTION:
Tratta della natura delle cose incorporate che non interagiscono con i corpi, come Dio e le cose divine.
GOLD:
 Tratta della natura delle cose incorporee, le quali non si trovano entro i corpi, come Dio e le cose divine
▶ Generating judgement ...
SCORE: 4

ORIGINAL:
 Dio, per la quale si dispensano et iudicano tutte le cose.
PREDICTION:
Dio, per il quale si dispensano e si giudicano tutte le cose.
GOLD:
 Dio, attraverso il quale si amministrano e si giudicano tutte le cose
▶ Generating judgement ...
SCORE: 4

ORIGINAL:
 Unde gli poeti, parlando de lloro, dicono le virtute loro e dicono fabolosamente gli loro difetti, quando alcuna passava l'ordine a lloro deputato
PREDICTION:
Da ciò che dicono i poeti, parlando di sé stessi, raccontano le loro virtù e descrivono in modo straordinario i loro difetti, quando superano i limiti del loro ruolo.
GOLD:
 Perciò i poeti, parlando di loro, dicono le loro virtù e raccontano favolosamente i loro difetti, quando qualcuno superava l'ordine a loro assegnato
▶ Generating judgement ...
SCORE: 4

ORIGINAL:
 e quella cosa, la quale è diricta et onesta, e con virtute, quella sola penso essere lo bene.
PREDICTION:
e quella cosa, la quale è diretta e onesta, e con virtù, penso che sia l'unica cosa buona.
GOLD:
 E quella cosa, che è retta e onesta, e con virtù, quella sola penso essere il bene
▶ Generating judgement ...
SCORE: 4

ORIGINAL:
 Quando li serpenti invellenava di giorno alcuno Romano, allora iera la maraviglia a vedere come li Psille si combattevano al veleno, ché elli imolavano tutto inazzi della loro salive
PREDICTION:
Quando i serpenti si scontravano durante il giorno, era una meraviglia vedere come le vipere combattevano con il loro veleno, poiché si immolavano a vicenda con la loro saliva.
GOLD:
 Quando i serpenti avvelenavano durante il giorno qualche Romano, era una meraviglia vedere come i Psilli si combattevano con il veleno, poiché sacrificavano tutto nel loro stesso veleno
▶ Generating judgement ...
SCORE: 4

ORIGINAL:
 Dice il poeta: oh, che bella cosa è vedere apertamente con gli occhi quando tu glel fai diretro o in culo o in altro
PREDICTION:
Il poeta dice: oh, che bella cosa è vedere chiaramente con gli occhi quando tu glielo fai da dietro o dall'altra parte.
GOLD:
 Afferma il poeta: oh, che cosa bella vedere coi propri occhi quando tu glielo metti dietro o nel sedere o in altro
▶ Generating judgement ...
SCORE: 4

ORIGINAL:
 ma pur questo fu colpa tua, però che volesti cercare di vedere con gli occhi corporali la cosa invisibile.
PREDICTION:
ma fu davvero colpa tua, poiché hai voluto cercare di vedere con gli occhi fisici qualcosa di invisibile.
GOLD:
 Ma anche questa fu colpa tua, perché volevi cercare di vedere con gli occhi materiali ciò che è invisibile.
▶ Generating judgement ...
SCORE: 4

ORIGINAL:
 Vero è, ma non tine rispondo in questo tempo, perciò che ttu se' mio servo, o perciò ch' è tempo feriato, o perciò ch' io non debbo risponderti
PREDICTION:
Veramente, ma non posso risponderti ora, perciò che tu sei mio servo, o perché è un giorno festivo, o perché non dovrei risponderti.
GOLD:
 È vero, ma non ti rispondo in questo momento, perché tu sei mio servo, oppure perché è un giorno festivo, oppure perché non devo rispondert
▶ Generating judgement ...
SCORE: 4

ORIGINAL:
 sì convene che lli desse grande avere perché · lasciasse andare via.
PREDICTION:
sì convenne che gli dessero una grande somma perché lo lasciasse andare via.
GOLD:
 È giusto che gli dessi una grande somma perché se ne andasse
▶ Generating judgement ...
SCORE: 4

ORIGINAL:
 notabile esemplo a ciascuno che si guardasse di fare e di pensar tradigione, il servo, il quale gli avea accusati, fu francato, e fugli donata grande quantità di moneta
PREDICTION:
notevole esempio per chiunque si guardi dal fare e dal pensare di tradire: il servo, che li aveva accusati, fu scagionato e fu donata a lui una grande quantità di denaro.
GOLD:
 Un esempio importante per tutti coloro che vogliano guardarsi dal fare e dal pensare tradimento: il servo che li aveva accusati fu liberato e gli fu donata una grande somma di denaro
▶ Generating judgement ...
SCORE: 4

ORIGINAL:
 che sarebbe a llui cosa sconcia se ll'avesse commesso sì che lla colpa del servo e 'l gastigamento di Platone avesse meritato egualmente.
PREDICTION:
che sarebbe stato sconveniente per lui se l'avesse commessa, così che la colpa del servo e il castigo di Platone avrebbe meritato allo stesso modo.
GOLD:
 Sarebbe per lui cosa vergognosa se l’avesse commessa, tanto che avrebbe meritato sia la colpa del servo sia la punizione di Platone
▶ Generating judgement ...
SCORE: 4

ORIGINAL:
 mostroe massimamente le forze sue, dando lui re a questa cittade ne la quale nacque servo; al quale avvenne lunghissimamente lo imperio tenere
PREDICTION:
mostrò massimamente le sue forze, dando prova di essere re di questa città nella quale nacque servo; ciò che gli riuscì dopo molto tempo, riuscendo a tenere il potere.
GOLD:
 Mostrò soprattutto la sua forza, dandogli il regno di questa città in cui era nato servo; al quale capitò di governare per molto tempo
▶ Generating judgement ...
SCORE: 4

ORIGINAL:
 l' anima muta la sua forza per la propietade di quello corpo a cui ella si congiunge.
PREDICTION:
l'anima cambia la sua forza in base alla proprietà del corpo con cui si unisce.
GOLD:
 L'anima cambia la sua forza in base alle caratteristiche del corpo a cui si unisce
▶ Generating judgement ...
SCORE: 4

ORIGINAL:
 sono due già non in una carne, ma in uno spirito, cioè Iddio, e l' anima. Onde in altro luogo dice S. Paolo: Chi s' accosta a Dio è uno spirito
PREDICTION:

tokenizer_config.json:   0%|          | 0.00/49.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/625 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/996k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.96M [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/714M [00:00<?, ?B/s]

Loading BLEURT-20 model...

Downloading builder script:   0%|          | 0.00/5.20k [00:00<?, ?B/s]

Downloading data:   0%|          | 0.00/2.14G [00:00<?, ?B/s]

Computing checksums: 100%|##########| 1/1 [00:05<00:00,  5.76s/it]

I0000 00:00:1750641674.953118      19 gpu_device.cc:2022] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 8077 MB memory:  -> device: 0, name: Tesla P100-PCIE-16GB, pci bus id: 0000:00:04.0, compute capability: 6.0

Loading COMET-22 model...

Fetching 5 files:   0%|          | 0/5 [00:00<?, ?it/s]

hparams.yaml:   0%|          | 0.00/567 [00:00<?, ?B/s]

LICENSE:   0%|          | 0.00/9.69k [00:00<?, ?B/s]

checkpoints/model.ckpt:   0%|          | 0.00/2.32G [00:00<?, ?B/s]

README.md:   0%|          | 0.00/3.40k [00:00<?, ?B/s]

.gitattributes:   0%|          | 0.00/1.48k [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/9.10M [00:00<?, ?B/s]

config.json:   0%|          | 0.00/616 [00:00<?, ?B/s]

/usr/local/lib/python3.11/dist-packages/pytorch_lightning/core/saving.py:195: Found keys that are not in the model state dict but in the checkpoint: ['encoder.model.embeddings.position_ids']
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

Results for /kaggle/input/predicted/predicted_mistral.xlsx (saved to /kaggle/working/predicted_mistral_traduzioni_con_score_grammatic.xlsx):
                                            Sentence  \
0  quella guerra ben fatta l' opera perché etc. E...
1  crudele, e di tutte le colpe pigli vendetta, c...
2  Non d' altra forza d' animo fue ornato Ponzio ...
3  Se questo piace a tutti e se 'l tempo hae biso...
4  Officio di questa arte pare che sia dicere app...

                                          prediction  Score
0  Quella guerra fu condotta con grande abilità, ...      4
1  crudele, e di tutte le colpe prendi vendetta, ...      4
2  Non fu ornato di altro coraggio che Ponzio Auf...      4
3  Se questo piace a tutti e se il tempo richiede...      4
4  Sembra che il compito di questa arte sia quell...      4









Judging /kaggle/input/predicted/predicted_opus.csv, grammatic


ORIGINAL:
 quella guerra ben fatta l' opera perché etc. Et dall' altra parte Aiaces era uno cavaliere franco e prode all' arme, di gran guisa, ma non era pieno di grande senno
PREDICTION:
che la guerra ha fatto bene perché, ecc. Et, dall'altra parte, Aiaces era un cavaliere che era libero e valoroso alle armi, con grande forza, ma non era pieno di grande senso
GOLD:
 Quella guerra era ben condotta per l’impresa, eccetera. E d’altra parte Aiace era un cavaliere valoroso e audace in battaglia, di grande forza, ma non era dotato di grande saggezza
▶ Generating judgement ...

/usr/local/lib/python3.11/dist-packages/transformers/generation/configuration_utils.py:631: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.7` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/transformers/generation/configuration_utils.py:636: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.8` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/transformers/generation/configuration_utils.py:653: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `20` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

SCORE: 2

ORIGINAL:
 crudele, e di tutte le colpe pigli vendetta, come dice la legge, ed a neuno cavaliere perdoni che pecchi.
PREDICTION:
crudele, e vendetta per tutti i peccati, come dice la legge, e non perdonare nessun cavaliere per il peccato.
GOLD:
 Crudele, e si vendica di tutte le colpe, come prescrive la legge, e non perdona nessun cavaliere che sbagli
▶ Generating judgement ...
SCORE: 2

ORIGINAL:
 Non d' altra forza d' animo fue ornato Ponzio Aufidiano, romano cavaliere.
PREDICTION:
Ponzio Aufidiano, un cavaliere romano, era adornato senza altra forza della mente.
GOLD:
 Ponzio Aufidiano, cavaliere romano, non fu dotato di minore forza d’animo.
▶ Generating judgement ...
SCORE: 4

ORIGINAL:
 Se questo piace a tutti e se 'l tempo hae bisogno d'avere Pompeio per cavaliere e non per compagno, non riterrò più i fati.
PREDICTION:
Se questo piace a tutti noi e se c'è bisogno di tempo per avere Pompeo come cavaliere e non come compagno, non considererò più i destini.
GOLD:
 Se questa è la volontà comune, e le circostanze richiedono Pompeo come guida piuttosto che come pari, allora non mi opporrò più al destino
▶ Generating judgement ...
SCORE: 4

ORIGINAL:
 Officio di questa arte pare che sia dicere appostatamente per fare credere, fine è far credere per lo dire.
PREDICTION:
L'ufficio di questa arte sembra essere quello di parlare intenzionalmente per far credere a uno, la fine è quello di far credere a uno nel discorso.
GOLD:
 Il compito di quest’arte sembra essere il parlare in modo appropriato per convincere; il suo fine è far credere attraverso il discorso.
▶ Generating judgement ...
SCORE: 4

ORIGINAL:
 Ecco e larghi ventipiovoli caggiono delle risolute nebbie; e potresti credere che tutto il cielo cadesse nel mare
PREDICTION:
Ecco, ci sono grandi tempeste di vento che scorrono dalle nebbie fisse; e voi potete credere che tutti i cieli sono caduti nel mare.
GOLD:
 Ecco, larghi scrosci di pioggia cadono dalle nebbie dissolte; e potresti credere che tutto il cielo stia precipitando nel mare
▶ Generating judgement ...
SCORE: 1

ORIGINAL:
 Però che or chi spererebbe quello che eziandio questi che non vogliono ancora credere in Cristo, già veggiono con noi, e perché nol possono negare, stridono colli denti.
PREDICTION:
Per ora coloro che sperano in ciò che costoro non vogliono ancora credere in Cristo, ora vedono con noi, e perché non possono negarli, strillare i denti.
GOLD:
 Chi potrebbe dunque sperare ciò che anche coloro che ancora non vogliono credere in Cristo già vedono insieme a noi, e poiché non possono negarlo, digrignano i denti?
▶ Generating judgement ...
SCORE: 2

ORIGINAL:
 I vendimenti de' morti et le presure de' vivi fece la frode d'uno feroce re.
PREDICTION:
La vendetta dei morti e l'assicurazione dei vivi hanno reso la frode di un re feroce.
GOLD:
 La frode di un re feroce causò la vendita dei beni dei morti e le pressioni sui vivi.
▶ Generating judgement ...
SCORE: 4

ORIGINAL:
 Acciocché quegli, il quale ora per le sue gran reità è feroce e onorevole, egli d'ogni male afflitto e tormentato della impietà verso il mio padre.
PREDICTION:
perché colui che ora è feroce e onorato per le sue grandi opere, sia tormentato e tormentato da ogni male per l'empietà verso mio padre.
GOLD:
 Affinché colui che ora, per le sue grandi colpe, è feroce e rispettato, sia afflitto e tormentato da ogni male a causa della sua empietà verso mio padre."
▶ Generating judgement ...
SCORE: 2

ORIGINAL:
 Gli uomini spessamente a stare fermi nella bugia incontra la verità.
PREDICTION:
Gli uomini spesso trovano la verità quando sono fermi nelle bugie.
GOLD:
 Gli uomini spesso, rimanendo fermi nella menzogna, incontrano la verità
▶ Generating judgement ...
SCORE: 4

ORIGINAL:
 Marco Cornelio ch'era de' dieci compagni, studiosamente  si riservò di parlare all'ultimo.
PREDICTION:
Marco Cornelio, che era uno dei dieci compagni, ha studiato attentamente per parlare con gli ultimi.
GOLD:
 Marco Cornelio, che faceva parte dei dieci compagni, con attenzione e prudenza si tenne per ultimo nel parlare
▶ Generating judgement ...
SCORE: 5

ORIGINAL:
 cose ch'io sapeva che erano fatte in Italia.
PREDICTION:
le cose che conoscevo sono state fatte in Italia.
GOLD:
 Cose che io sapevo essere state fatte in Italia
▶ Generating judgement ...
SCORE: 5

ORIGINAL:
 Corbio nipote d' Ortensio menò sua vita più bassa e più viziosa
PREDICTION:
Corbio il nipote di Hortensus ha portato la sua vita a inferiore e più vizioso
GOLD:
 Corbio, nipote di Ortensio, condusse una vita più bassa e più viziosa
▶ Generating judgement ...
SCORE: 2

ORIGINAL:
 Altressì uno amante chiamando merzé alla sua donna dice parole e ragioni molte, et ella si difende in suo dire.
PREDICTION:
Eppure un amante, chiamando merito alla sua signora, parla molte parole e ragioni, e lei si difende nel suo discorso.
GOLD:
 Allo stesso modo, un amante chiamando merzé (rimprovero) alla sua donna dice molte parole e ragioni, e lei si difende nel suo discorso
▶ Generating judgement ...
SCORE: 4

ORIGINAL:
 Io mi ricordo (ch. 347) che essendo adirato scapigliai la mia donna. Ohi, quanti dì questa ira mi tolse!
PREDICTION:
Ricordo (cf. 347) che, mentre ero arrabbiato, vagavo per la mia signora. Oh, quanti giorni questa rabbia mi ha portato via!
GOLD:
 Ricordo che, essendo arrabbiato, misi in disordine i capelli della mia donna. Oh, quanti giorni questa collera mi tolse
▶ Generating judgement ...
SCORE: 4

ORIGINAL:
 colui del quale tu tti solevi dolere ch' era amante della tua donna;
PREDICTION:
quella che avevi in lutto per chi era amante della tua donna;
GOLD:
 Colui del quale tu eri solito dolerti perché era amante della tua donna
▶ Generating judgement ...
SCORE: 2

ORIGINAL:
 Ma no sapeano già le nomora di coloro dela congiurazione, ché la donna no nominava già li nomi.
PREDICTION:
Ma non conoscevano già i nomi di coloro che si evocano, perché nessuna donna aveva già chiamato i nomi.
GOLD:
 Ma non conoscevano ancora i nomi di coloro della congiura, perché la donna non aveva ancora nominato i nomi
▶ Generating judgement ...
SCORE: 5

ORIGINAL:
 Creti?  Certo quand'elli si mosse, elli ti dixe: "O fedele mia donna, fa' che in mio luogo ti sia racomandato il nostro hoste troiano".
PREDICTION:
Pensate? Quando egli andò avanti, vi disse: "O mia fedele signora, lasciate che il nostro ostia di Troia sia rimandato a voi al mio posto.
GOLD:
 Creti? Certo, quando lui si mosse, ti disse: 'O mia fedele donna, fa’ che sia raccomandato a te, al mio posto, il nostro ospite troiano
▶ Generating judgement ...
SCORE: 4

ORIGINAL:
 A Milano fue ripressa la malvagità d' una donna in simile bugìa, nel tempo medesimo di questo signore della republica, in questo modo:
PREDICTION:
A Milano, la malvagità di una donna in una tale menzogna è stata repressa, allo stesso tempo di questo signore della repubblica, in questo modo:
GOLD:
 A Milano fu scoperta la malvagità di una donna in una simile menzogna, nel medesimo tempo di questo signore della repubblica, in questo modo
▶ Generating judgement ...
SCORE: 4

ORIGINAL:
 E lamentavansi dell'iniquità d'Appio, e ripiagnevano la malavventurata beltà della pulcella e la necessità del padre.
PREDICTION:
E lamentarono le iniquità di Appio, e lamentarono la malavventura della bellezza del toro e il bisogno di suo padre.
GOLD:
 Si lamentavano dell’ingiustizia di Appio, e piangevano per la sfortunata bellezza della ragazza e per la necessità del padre
▶ Generating judgement ...
SCORE: 2

ORIGINAL:
 Nella quale battaglia, certo io ebbi sempre ardire di ragionare di pace e sempre mi dolfi che non solamente la pace era schifata,
PREDICTION:
In quella battaglia, certamente avevo sempre osato ragionare per la pace, e dormo sempre che non solo era disgustata la pace,
GOLD:
 In quella battaglia, certamente ebbi sempre il coraggio di parlare di pace, e mi dolevo che non solo la pace fosse disprezzata
▶ Generating judgement ...
SCORE: 2

ORIGINAL:
 la seconda suole talora per la grande provedenzia fare timoroso, e la prima per l'ardire rendere altrui matto.
PREDICTION:
il secondo, a volte, è usato dalla grande Provvidenza per fare paura, e il primo, attraverso l'audace, per far impazzire gli altri.
GOLD:
 La seconda talvolta, a causa della grande prudenza, rende timoroso, e la prima , per l’audacia, fa diventare pazzo qualcun altro
▶ Generating judgement ...
SCORE: 4

ORIGINAL:
 Andò nel campo de' Cartaginesi e tutta la legione trasse seco.
PREDICTION:
Entrò nel campo dei Cartaginesi e trasse con sé tutta la legione.
GOLD:
 Entrò nel campo dei Cartaginesi e condusse con sé tutta la legione
▶ Generating judgement ...
SCORE: 4

ORIGINAL:
 Non lo volle cognoscere per nimico. Qesta è quella, la quale diede ardire al profeta Natan a riprendere con grande autoritade quello re, il quale avea peccato.
PREDICTION:
Egli non voleva conoscerlo come un nemico. Questo è ciò che lei, che diede al profeta Natan il coraggio di rimproverare con grande autorità quel re, che aveva peccato.
GOLD:
 Non lo volle riconoscere come nemico. Questa è colei che diede coraggio al profeta Natan a riprendere con grande autorità quel re che aveva peccato
▶ Generating judgement ...
SCORE: 4

ORIGINAL:
 l'armi et insieme con loro passaseno tra li nimici, perçò se alcuno non avesse ardire de questo et sì avevano questo animo.
PREDICTION:
le braccia e, insieme con loro, passarono in mezzo al nemico, perché se qualcuno non avesse osato questo, e così aveva questa mente.
GOLD:
 Le armi e insieme con esse passarono tra i nemici, perciò se qualcuno non avesse avuto coraggio in ciò, non avrebbe avuto questo spirito
▶ Generating judgement ...
SCORE: 4

ORIGINAL:
 Unde ragionevolemente Iob è interpretato dolente;
PREDICTION:
Unde seguendo, Giobbe è interpretato come disgustoso;
GOLD:
 Per questo, ragionevolmente, Giobbe è interpretato come dolente
▶ Generating judgement ...
SCORE: 2

ORIGINAL:
 quello che sopra tutti gli altri perdonasse a' cittadini, e a cui più sicuramente possiate credere; poi ch'egli fu vostro comandatore.
PREDICTION:
colui che, sopra tutti gli altri, ha perdonato i cittadini, e a cui si può sicuramente credere, poiché era il vostro capo.
GOLD:
 Colui che perdonava più di tutti gli altri i cittadini, e a cui potete credere con maggior sicurezza; poiché egli fu vostro comandante
▶ Generating judgement ...
SCORE: 4

ORIGINAL:
 in vano si domanda chi questo Libro scrivesse, con ciò sia cosa che fedelmente si debba credere che l'Auttore di quello fusse lo Spirito santo.
PREDICTION:
Invano, uno si meraviglia chi ha scritto questo Libro, con il quale si deve credere fedelmente che l'Autore di questo è stato lo Spirito Santo.
GOLD:
 Invano si domanda chi abbia scritto questo Libro, poiché si deve credere fedelmente che l’Autore di esso sia lo Spirito Santo.
▶ Generating judgement ...
SCORE: 4

ORIGINAL:
 se non fosse usatissima, ciò parrebbe certo molto più incredibile: certo più agevolmente si può credere quello, posto che l'umano spirito al divino, ed il mutabile allo incommutabile
PREDICTION:
se non fosse usato di più, questo sembrerebbe certamente molto più incredibile: sicuramente si può credere che più facilmente dello spirito umano al divino, e l'immutabile all'immutabile
GOLD:
 Se non fosse così frequentemente usata, questa cosa sembrerebbe certamente molto più incredibile; invece è più facile credere a ciò, dato che lo spirito umano si riferisce a quello divino, e ciò che è mutevole a ciò che è incorruttibile
▶ Generating judgement ...
SCORE: 2

ORIGINAL:
 che prendessero la paga dal camarlingo per loro dispensa et immantenente andassero alla presenzia di messer lo papa per contradiare il passamento de' cavalieri che veniano di Cecilia in Toscana
PREDICTION:
che hanno preso la loro paga dai Camarlingo per la loro dispensa, e immanente, per andare alla presenza del Papa per contraddire il passaggio dei cavalieri che sono venuti da Cecilia in Toscana
GOLD:
 Che prendessero la paga dal camerlingo per la loro dispensa e immediatamente andassero alla presenza di messer il papa per ostacolare il passaggio dei cavalieri che venivano da Cecilia in Toscana.
▶ Generating judgement ...
SCORE: 4

ORIGINAL:
 Teseo reguardò Achelao fortemente meravigliandose e disse così: "O messer Achelao, io vi prego che voi me diciate in che modo voi perdeste
PREDICTION:
Teseo guardò con attenzione Achelaus e disse: "O Messer Achelaus, ti prego di dirmi come hai perso
GOLD:
 Teseo guardò Achelao con grande stupore e disse: 'O messer Achelao, vi prego di dirmi come avete perso
▶ Generating judgement ...
SCORE: 4

ORIGINAL:
 Io spero in messer Iesù di mandare tosto a voi Timoteo, acciocché io sia d'animo buono
PREDICTION:
Spero che Messer Gesù manderà presto Timoteo a voi, affinché io possa essere di buona mente
GOLD:
 Spero in messer Gesù di mandare presto a voi Timoteo, affinché io possa avere buon animo
▶ Generating judgement ...
SCORE: 4

ORIGINAL:
 sanza fallo lo porco salvatico avanza l' uomo d' udire e 'l lupo cerviere del vedere
PREDICTION:
senza successo, il maiale che è salvato avanza l'uomo a sentire e il lupo che è il cervo di vedere
GOLD:
 Senza dubbio il cinghiale selvatico supera l’uomo nell’udito e il lupo nel vedere
▶ Generating judgement ...
SCORE: 2

ORIGINAL:
 uno luogo si mandano lancioni;  la quale cosa i cavalieri l' appellano capo di porco
PREDICTION:
un luogo è mandato da tuoni, quello che i cavalieri chiamano la testa di un maiale
GOLD:
 In un punto si inviano lance; questa manovra i cavalieri la chiamano 'capo di porco'
▶ Generating judgement ...
SCORE: 4

ORIGINAL:
 tenda le reti a li cerbi e sa bene in quali valle dimori il furioso porco cinghiare.
PREDICTION:
tende le reti al cervo, e sa bene in quale valle sta il maiale furioso.
GOLD:
 Tende le reti per i cerbiatti e conosce bene in quali valli dimora il feroce cinghiale
▶ Generating judgement ...
SCORE: 2

ORIGINAL:
 Ora spaventerai li disidirosi cervi con varie e diverse paure, o lo porco cenghiare caggia in terra passato collo spiedo.
PREDICTION:
Ora sarete terrorizzati dal cervo dissidioso con paure diverse e diverse, o il maiale che i cedri cadono per terra, passato, collo di spiedo.
GOLD:
 Ora spaventerai i cervi timorosi con varie e molte paure, o il cinghiale cadrà a terra infilzato dallo spiedo
▶ Generating judgement ...
SCORE: 2

ORIGINAL:
 tratta la natura delle cose incorporali le quali non conversano intra lle corpora, sì come Dio e le divine cose.
PREDICTION:
tratta la natura delle cose che sono incorporate nel corpo; non convergono all'interno del corpo, proprio come Dio e le cose divine fanno.
GOLD:
 Tratta della natura delle cose incorporee, le quali non si trovano entro i corpi, come Dio e le cose divine
▶ Generating judgement ...
SCORE: 4

ORIGINAL:
 Dio, per la quale si dispensano et iudicano tutte le cose.
PREDICTION:
Dio, per mezzo del quale tutte le cose sono dispensate e servite.
GOLD:
 Dio, attraverso il quale si amministrano e si giudicano tutte le cose
▶ Generating judgement ...
SCORE: 4

ORIGINAL:
 Unde gli poeti, parlando de lloro, dicono le virtute loro e dicono fabolosamente gli loro difetti, quando alcuna passava l'ordine a lloro deputato
PREDICTION:
I poeti, quando parlano di loro, parlano delle loro virtù e parlano delle loro colpe, quando alcuni di loro passarono l'ordine al loro vice
GOLD:
 Perciò i poeti, parlando di loro, dicono le loro virtù e raccontano favolosamente i loro difetti, quando qualcuno superava l'ordine a loro assegnato
▶ Generating judgement ...
SCORE: 4

ORIGINAL:
 e quella cosa, la quale è diricta et onesta, e con virtute, quella sola penso essere lo bene.
PREDICTION:
e quella cosa, che è diretta e onesta, e con virtù, quella, credo, è la buona.
GOLD:
 E quella cosa, che è retta e onesta, e con virtù, quella sola penso essere il bene
▶ Generating judgement ...
SCORE: 4

ORIGINAL:
 Quando li serpenti invellenava di giorno alcuno Romano, allora iera la maraviglia a vedere come li Psille si combattevano al veleno, ché elli imolavano tutto inazzi della loro salive
PREDICTION:
Quando i serpenti invasero di giorno alcuni romani, allora si domandarono come i Phillips combattessero contro il veleno, perché era tutta la rabbia dei loro alberelli.
GOLD:
 Quando i serpenti avvelenavano durante il giorno qualche Romano, era una meraviglia vedere come i Psilli si combattevano con il veleno, poiché sacrificavano tutto nel loro stesso veleno
▶ Generating judgement ...
SCORE: 1

ORIGINAL:
 Dice il poeta: oh, che bella cosa è vedere apertamente con gli occhi quando tu glel fai diretro o in culo o in altro
PREDICTION:
Il poeta dice: Oh, che cosa bella è vedere apertamente con gli occhi quando li fai guardare giù sul tuo culo o sul tuo culo
GOLD:
 Afferma il poeta: oh, che cosa bella vedere coi propri occhi quando tu glielo metti dietro o nel sedere o in altro
▶ Generating judgement ...
SCORE: 2

ORIGINAL:
 ma pur questo fu colpa tua, però che volesti cercare di vedere con gli occhi corporali la cosa invisibile.
PREDICTION:
Ma e' stata colpa tua, perche' volevi provare a vedere la cosa invisibile con gli occhi del corpo.
GOLD:
 Ma anche questa fu colpa tua, perché volevi cercare di vedere con gli occhi materiali ciò che è invisibile.
▶ Generating judgement ...
SCORE: 2

ORIGINAL:
 Vero è, ma non tine rispondo in questo tempo, perciò che ttu se' mio servo, o perciò ch' è tempo feriato, o perciò ch' io non debbo risponderti
PREDICTION:
È vero, ma in questo momento non rispondo, perché è per questo che il mio servo è, o perché è ferito, o perché non devo rispondere
GOLD:
 È vero, ma non ti rispondo in questo momento, perché tu sei mio servo, oppure perché è un giorno festivo, oppure perché non devo rispondert
▶ Generating judgement ...
SCORE: 4

ORIGINAL:
 sì convene che lli desse grande avere perché · lasciasse andare via.
PREDICTION:
perché dia loro un grande potere per lasciarli andare.
GOLD:
 È giusto che gli dessi una grande somma perché se ne andasse
▶ Generating judgement ...
SCORE: 2

ORIGINAL:
 notabile esemplo a ciascuno che si guardasse di fare e di pensar tradigione, il servo, il quale gli avea accusati, fu francato, e fugli donata grande quantità di moneta
PREDICTION:
un esempio notevole a ciascuno che guardava se stesso per fare e per pensare tradimento, il servo, che lo aveva accusato, è stato liberato, e gli è stato dato una grande quantità di denaro
GOLD:
 Un esempio importante per tutti coloro che vogliano guardarsi dal fare e dal pensare tradimento: il servo che li aveva accusati fu liberato e gli fu donata una grande somma di denaro
▶ Generating judgement ...
SCORE: 4

ORIGINAL:
 che sarebbe a llui cosa sconcia se ll'avesse commesso sì che lla colpa del servo e 'l gastigamento di Platone avesse meritato egualmente.
PREDICTION:
che sarebbe una cosa sporca per lui se l'avesse commesso in modo che Platos colpa e gastificazione aveva ugualmente meritato.
GOLD:
 Sarebbe per lui cosa vergognosa se l’avesse commessa, tanto che avrebbe meritato sia la colpa del servo sia la punizione di Platone
▶ Generating judgement ...
SCORE: 2

ORIGINAL:
 mostroe massimamente le forze sue, dando lui re a questa cittade ne la quale nacque servo; al quale avvenne lunghissimamente lo imperio tenere
PREDICTION:
Egli mostrò la sua forza in gran parte, dandogli re in questa città in cui nacque servo; a cui l'impero fu tenuto per lungo tempo
GOLD:
 Mostrò soprattutto la sua forza, dandogli il regno di questa città in cui era nato servo; al quale capitò di governare per molto tempo
▶ Generating judgement ...
SCORE: 4

ORIGINAL:
 l' anima muta la sua forza per la propietade di quello corpo a cui ella si congiunge.
PREDICTION:
l'anima cambia la sua forza attraverso il propiziato di quel corpo a cui si unisce.
GOLD:
 L'anima cambia la sua forza in base alle caratteristiche del corpo a cui si unisce
▶ Generating judgement ...
SCORE: 2

ORIGINAL:
 sono due già non in una carne, ma in uno spirito, cioè Iddio, e l' anima. Onde in altro luogo dice S. Paolo: Chi s' accosta a Dio è uno spirito
PREDICTION:

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

Results for /kaggle/input/predicted/predicted_opus.csv (saved to /kaggle/working/predicted_opus_traduzioni_con_score_grammatic.xlsx):
                                            Sentence  \
0  quella guerra ben fatta l' opera perché etc. E...
1  crudele, e di tutte le colpe pigli vendetta, c...
2  Non d' altra forza d' animo fue ornato Ponzio ...
3  Se questo piace a tutti e se 'l tempo hae biso...
4  Officio di questa arte pare che sia dicere app...

                                          prediction  Score
0  che la guerra ha fatto bene perché, ecc. Et, d...      2
1  crudele, e vendetta per tutti i peccati, come ...      2
2  Ponzio Aufidiano, un cavaliere romano, era ado...      4
3  Se questo piace a tutti noi e se c'è bisogno d...      4
4  L'ufficio di questa arte sembra essere quello ...      4









Judging /kaggle/input/predicted/predicted_mistral.xlsx, semantic


ORIGINAL:
 quella guerra ben fatta l' opera perché etc. Et dall' altra parte Aiaces era uno cavaliere franco e prode all' arme, di gran guisa, ma non era pieno di grande senno
PREDICTION:
Quella guerra fu condotta con grande abilità, ecc. Dall'altra parte, Aiace era un cavaliere coraggioso e abile nella guerra, di grande aspetto, ma non era pieno di grande senno.
GOLD:
 Quella guerra era ben condotta per l’impresa, eccetera. E d’altra parte Aiace era un cavaliere valoroso e audace in battaglia, di grande forza, ma non era dotato di grande saggezza
▶ Generating judgement ...

/usr/local/lib/python3.11/dist-packages/transformers/generation/configuration_utils.py:631: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.7` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/transformers/generation/configuration_utils.py:636: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.8` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/transformers/generation/configuration_utils.py:653: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `20` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

SCORE: 3

ORIGINAL:
 crudele, e di tutte le colpe pigli vendetta, come dice la legge, ed a neuno cavaliere perdoni che pecchi.
PREDICTION:
crudele, e di tutte le colpe prendi vendetta, come dice la legge, e non perdonare a nessun cavaliere che pecchi.
GOLD:
 Crudele, e si vendica di tutte le colpe, come prescrive la legge, e non perdona nessun cavaliere che sbagli
▶ Generating judgement ...
SCORE: 2

ORIGINAL:
 Non d' altra forza d' animo fue ornato Ponzio Aufidiano, romano cavaliere.
PREDICTION:
Non fu ornato di altro coraggio che Ponzio Aufidiano, cavaliere romano.
GOLD:
 Ponzio Aufidiano, cavaliere romano, non fu dotato di minore forza d’animo.
▶ Generating judgement ...
SCORE: 2

ORIGINAL:
 Se questo piace a tutti e se 'l tempo hae bisogno d'avere Pompeio per cavaliere e non per compagno, non riterrò più i fati.
PREDICTION:
Se questo piace a tutti e se il tempo richiede che Pompeo sia il cavaliere e non il compagno, non mi opporrò più al fato.
GOLD:
 Se questa è la volontà comune, e le circostanze richiedono Pompeo come guida piuttosto che come pari, allora non mi opporrò più al destino
▶ Generating judgement ...
SCORE: 3

ORIGINAL:
 Officio di questa arte pare che sia dicere appostatamente per fare credere, fine è far credere per lo dire.
PREDICTION:
Sembra che il compito di questa arte sia quello di dire appositamente le cose per farle credere, il fine è convincere con le parole.
GOLD:
 Il compito di quest’arte sembra essere il parlare in modo appropriato per convincere; il suo fine è far credere attraverso il discorso.
▶ Generating judgement ...
SCORE: 3

ORIGINAL:
 Ecco e larghi ventipiovoli caggiono delle risolute nebbie; e potresti credere che tutto il cielo cadesse nel mare
PREDICTION:
Ecco, come grandi gocce di pioggia cadono dalle risolute nebbie; e potresti giurare che tutto il cielo stia crollando nel mare.
GOLD:
 Ecco, larghi scrosci di pioggia cadono dalle nebbie dissolte; e potresti credere che tutto il cielo stia precipitando nel mare
▶ Generating judgement ...
SCORE: 3

ORIGINAL:
 Però che or chi spererebbe quello che eziandio questi che non vogliono ancora credere in Cristo, già veggiono con noi, e perché nol possono negare, stridono colli denti.
PREDICTION:
Perciò, chi ora spererebbe che anche coloro che ancora non vogliono credere in Cristo, vedano con noi, e poiché non possono negarlo, siano costretti a serrare i denti.
GOLD:
 Chi potrebbe dunque sperare ciò che anche coloro che ancora non vogliono credere in Cristo già vedono insieme a noi, e poiché non possono negarlo, digrignano i denti?
▶ Generating judgement ...
SCORE: 4

ORIGINAL:
 I vendimenti de' morti et le presure de' vivi fece la frode d'uno feroce re.
PREDICTION:
Le spoglie dei morti e le pretese dei vivi furono la frode di un re feroce.
GOLD:
 La frode di un re feroce causò la vendita dei beni dei morti e le pressioni sui vivi.
▶ Generating judgement ...
SCORE: 3

ORIGINAL:
 Acciocché quegli, il quale ora per le sue gran reità è feroce e onorevole, egli d'ogni male afflitto e tormentato della impietà verso il mio padre.
PREDICTION:
Affinché colui, che ora per le sue grandi imprese è feroce e onorevole, soffra e sia tormentato da ogni male a causa della sua impietà verso mio padre.
GOLD:
 Affinché colui che ora, per le sue grandi colpe, è feroce e rispettato, sia afflitto e tormentato da ogni male a causa della sua empietà verso mio padre."
▶ Generating judgement ...
SCORE: 4

ORIGINAL:
 Gli uomini spessamente a stare fermi nella bugia incontra la verità.
PREDICTION:
Gli uomini spesso incontrano la verità stando fermi nella bugia.
GOLD:
 Gli uomini spesso, rimanendo fermi nella menzogna, incontrano la verità
▶ Generating judgement ...
SCORE: 4

ORIGINAL:
 Marco Cornelio ch'era de' dieci compagni, studiosamente  si riservò di parlare all'ultimo.
PREDICTION:
Marco Cornelio, che era uno dei dieci compagni, si riservò di parlare per ultimo, con attenzione.
GOLD:
 Marco Cornelio, che faceva parte dei dieci compagni, con attenzione e prudenza si tenne per ultimo nel parlare
▶ Generating judgement ...
SCORE: 3

ORIGINAL:
 cose ch'io sapeva che erano fatte in Italia.
PREDICTION:
cose che sapevo essere fatte in Italia.
GOLD:
 Cose che io sapevo essere state fatte in Italia
▶ Generating judgement ...
SCORE: 3

ORIGINAL:
 Corbio nipote d' Ortensio menò sua vita più bassa e più viziosa
PREDICTION:
Corbio, nipote di Ortensio, condusse una vita più bassa e più viziosa.
GOLD:
 Corbio, nipote di Ortensio, condusse una vita più bassa e più viziosa
▶ Generating judgement ...
SCORE: 4

ORIGINAL:
 Altressì uno amante chiamando merzé alla sua donna dice parole e ragioni molte, et ella si difende in suo dire.
PREDICTION:
Allo stesso modo, un amante chiamando misericordia dalla sua donna dice parole e ragioni tante, e lei si difende in quello che dice.
GOLD:
 Allo stesso modo, un amante chiamando merzé (rimprovero) alla sua donna dice molte parole e ragioni, e lei si difende nel suo discorso
▶ Generating judgement ...
SCORE: 3

ORIGINAL:
 Io mi ricordo (ch. 347) che essendo adirato scapigliai la mia donna. Ohi, quanti dì questa ira mi tolse!
PREDICTION:
Mi ricordo (c. 347) che, essendo arrabbiato, le sbarrai la strada con la mia donna. Ohimè, quante giornate mi ha fatto passare questa rabbia!
GOLD:
 Ricordo che, essendo arrabbiato, misi in disordine i capelli della mia donna. Oh, quanti giorni questa collera mi tolse
▶ Generating judgement ...
SCORE: 2

ORIGINAL:
 colui del quale tu tti solevi dolere ch' era amante della tua donna;
PREDICTION:
colui del quale tu eri solita lamentarti, era l'amante della tua donna.
GOLD:
 Colui del quale tu eri solito dolerti perché era amante della tua donna
▶ Generating judgement ...
SCORE: 3

ORIGINAL:
 Ma no sapeano già le nomora di coloro dela congiurazione, ché la donna no nominava già li nomi.
PREDICTION:
Ma non sapevano ancora i nomi di coloro della congiura, poiché la donna non aveva ancora menzionato i nomi.
GOLD:
 Ma non conoscevano ancora i nomi di coloro della congiura, perché la donna non aveva ancora nominato i nomi
▶ Generating judgement ...
SCORE: 4

ORIGINAL:
 Creti?  Certo quand'elli si mosse, elli ti dixe: "O fedele mia donna, fa' che in mio luogo ti sia racomandato il nostro hoste troiano".
PREDICTION:
Creti? Certo, quando lui si mosse, lui ti disse: "Oh mia fedele donna, assicurati che il nostro ospite troiano sia raccomandato al mio posto".
GOLD:
 Creti? Certo, quando lui si mosse, ti disse: 'O mia fedele donna, fa’ che sia raccomandato a te, al mio posto, il nostro ospite troiano
▶ Generating judgement ...
SCORE: 3

ORIGINAL:
 A Milano fue ripressa la malvagità d' una donna in simile bugìa, nel tempo medesimo di questo signore della republica, in questo modo:
PREDICTION:
A Milano fu repressa la malvagità di una donna che mentiva, nello stesso periodo di questo signore della repubblica, in questo modo:
GOLD:
 A Milano fu scoperta la malvagità di una donna in una simile menzogna, nel medesimo tempo di questo signore della repubblica, in questo modo
▶ Generating judgement ...
SCORE: 3

ORIGINAL:
 E lamentavansi dell'iniquità d'Appio, e ripiagnevano la malavventurata beltà della pulcella e la necessità del padre.
PREDICTION:
Si lamentavano dell'ingiustizia di Appio e piangevano per la sventurata bellezza della fanciulla e per la necessità del padre.
GOLD:
 Si lamentavano dell’ingiustizia di Appio, e piangevano per la sfortunata bellezza della ragazza e per la necessità del padre
▶ Generating judgement ...
SCORE: 4

ORIGINAL:
 Nella quale battaglia, certo io ebbi sempre ardire di ragionare di pace e sempre mi dolfi che non solamente la pace era schifata,
PREDICTION:
In tale battaglia, io mi sono sempre adoperato per parlare di pace e ho sempre pensato che non solo la pace fosse disprezzata,
GOLD:
 In quella battaglia, certamente ebbi sempre il coraggio di parlare di pace, e mi dolevo che non solo la pace fosse disprezzata
▶ Generating judgement ...
SCORE: 3

ORIGINAL:
 la seconda suole talora per la grande provedenzia fare timoroso, e la prima per l'ardire rendere altrui matto.
PREDICTION:
Il secondo [evento] a volte fa temere per la grande provenienza, e il primo per ardire rende l'altro pazzo.
GOLD:
 La seconda talvolta, a causa della grande prudenza, rende timoroso, e la prima , per l’audacia, fa diventare pazzo qualcun altro
▶ Generating judgement ...
SCORE: 3

ORIGINAL:
 Andò nel campo de' Cartaginesi e tutta la legione trasse seco.
PREDICTION:
Andò nel campo dei Cartaginesi e portò con sé tutta la legione.
GOLD:
 Entrò nel campo dei Cartaginesi e condusse con sé tutta la legione
▶ Generating judgement ...
SCORE: 4

ORIGINAL:
 Non lo volle cognoscere per nimico. Qesta è quella, la quale diede ardire al profeta Natan a riprendere con grande autoritade quello re, il quale avea peccato.
PREDICTION:
Non voleva riconoscerlo come nemico. Questa è lei, la donna che diede il coraggio al profeta Nathan di rimproverare con grande autorevolezza il re, che aveva peccato.
GOLD:
 Non lo volle riconoscere come nemico. Questa è colei che diede coraggio al profeta Natan a riprendere con grande autorità quel re che aveva peccato
▶ Generating judgement ...
SCORE: 3

ORIGINAL:
 l'armi et insieme con loro passaseno tra li nimici, perçò se alcuno non avesse ardire de questo et sì avevano questo animo.
PREDICTION:
E con loro passavano le armi, perciò se qualcuno non avesse avuto il coraggio di fare questo, e così era nel loro animo.
GOLD:
 Le armi e insieme con esse passarono tra i nemici, perciò se qualcuno non avesse avuto coraggio in ciò, non avrebbe avuto questo spirito
▶ Generating judgement ...
SCORE: 3

ORIGINAL:
 Unde ragionevolemente Iob è interpretato dolente;
PREDICTION:
Per questo motivo, Giobbe viene interpretato come sofferente.
GOLD:
 Per questo, ragionevolmente, Giobbe è interpretato come dolente
▶ Generating judgement ...
SCORE: 3

ORIGINAL:
 quello che sopra tutti gli altri perdonasse a' cittadini, e a cui più sicuramente possiate credere; poi ch'egli fu vostro comandatore.
PREDICTION:
colui che perdonò più di tutti agli altri ai cittadini, e a cui potete credere più sicuramente; poiché egli era il vostro comandante.
GOLD:
 Colui che perdonava più di tutti gli altri i cittadini, e a cui potete credere con maggior sicurezza; poiché egli fu vostro comandante
▶ Generating judgement ...
SCORE: 3

ORIGINAL:
 in vano si domanda chi questo Libro scrivesse, con ciò sia cosa che fedelmente si debba credere che l'Auttore di quello fusse lo Spirito santo.
PREDICTION:
Inutilmente si chiede chi abbia scritto questo Libro, dato che è una verità che fedelmente si deve credere che l'Autore sia lo Spirito Santo.
GOLD:
 Invano si domanda chi abbia scritto questo Libro, poiché si deve credere fedelmente che l’Autore di esso sia lo Spirito Santo.
▶ Generating judgement ...
SCORE: 4

ORIGINAL:
 se non fosse usatissima, ciò parrebbe certo molto più incredibile: certo più agevolmente si può credere quello, posto che l'umano spirito al divino, ed il mutabile allo incommutabile
PREDICTION:
se non fosse una frase così comune, suonerebbe certamente come qualcosa di incredibile: è molto più facile credere che l'umano possa assomigliare al divino, e il mutevole all'immutabile.
GOLD:
 Se non fosse così frequentemente usata, questa cosa sembrerebbe certamente molto più incredibile; invece è più facile credere a ciò, dato che lo spirito umano si riferisce a quello divino, e ciò che è mutevole a ciò che è incorruttibile
▶ Generating judgement ...
SCORE: 3

ORIGINAL:
 che prendessero la paga dal camarlingo per loro dispensa et immantenente andassero alla presenzia di messer lo papa per contradiare il passamento de' cavalieri che veniano di Cecilia in Toscana
PREDICTION:
he prendessero la paga dal tesoriere per la loro spesa e immediatamente andassero da mastro il papa per contraddire il passaggio dei cavalieri che venivano da Cecilia in Toscana.
GOLD:
 Che prendessero la paga dal camerlingo per la loro dispensa e immediatamente andassero alla presenza di messer il papa per ostacolare il passaggio dei cavalieri che venivano da Cecilia in Toscana.
▶ Generating judgement ...
SCORE: 2

ORIGINAL:
 Teseo reguardò Achelao fortemente meravigliandose e disse così: "O messer Achelao, io vi prego che voi me diciate in che modo voi perdeste
PREDICTION:
Teseo lo guardò Achelao con stupore e disse: "Oh signor Achelao, vi prego, dimmi come hai perso"
GOLD:
 Teseo guardò Achelao con grande stupore e disse: 'O messer Achelao, vi prego di dirmi come avete perso
▶ Generating judgement ...
SCORE: 3

ORIGINAL:
 Io spero in messer Iesù di mandare tosto a voi Timoteo, acciocché io sia d'animo buono
PREDICTION:
Spero in messer Gesù di mandarti presto Timoteo, per tranquillizzare la mia mente.
GOLD:
 Spero in messer Gesù di mandare presto a voi Timoteo, affinché io possa avere buon animo
▶ Generating judgement ...
SCORE: 3

ORIGINAL:
 sanza fallo lo porco salvatico avanza l' uomo d' udire e 'l lupo cerviere del vedere
PREDICTION:
senza dubbio il selvatico porco avanza l'uomo nell'ascolto e il lupo nel vedere.
GOLD:
 Senza dubbio il cinghiale selvatico supera l’uomo nell’udito e il lupo nel vedere
▶ Generating judgement ...
SCORE: 2

ORIGINAL:
 uno luogo si mandano lancioni;  la quale cosa i cavalieri l' appellano capo di porco
PREDICTION:
un luogo dove si mandano lance; la quale cosa i cavalieri chiamano "testa di maiale"
GOLD:
 In un punto si inviano lance; questa manovra i cavalieri la chiamano 'capo di porco'
▶ Generating judgement ...
SCORE: 3

ORIGINAL:
 tenda le reti a li cerbi e sa bene in quali valle dimori il furioso porco cinghiare.
PREDICTION:
tenda le reti ai cervi e sa bene in quale valle dimori il selvaggio maiale incorni.
GOLD:
 Tende le reti per i cerbiatti e conosce bene in quali valli dimora il feroce cinghiale
▶ Generating judgement ...
SCORE: 3

ORIGINAL:
 Ora spaventerai li disidirosi cervi con varie e diverse paure, o lo porco cenghiare caggia in terra passato collo spiedo.
PREDICTION:
Ora spaventerai i cervi disidratati con varie e diverse paure, o il maiale selvatico cadrà a terra trafitto dallo spiedo.
GOLD:
 Ora spaventerai i cervi timorosi con varie e molte paure, o il cinghiale cadrà a terra infilzato dallo spiedo
▶ Generating judgement ...
SCORE: 2

ORIGINAL:
 tratta la natura delle cose incorporali le quali non conversano intra lle corpora, sì come Dio e le divine cose.
PREDICTION:
Tratta della natura delle cose incorporate che non interagiscono con i corpi, come Dio e le cose divine.
GOLD:
 Tratta della natura delle cose incorporee, le quali non si trovano entro i corpi, come Dio e le cose divine
▶ Generating judgement ...
SCORE: 3

ORIGINAL:
 Dio, per la quale si dispensano et iudicano tutte le cose.
PREDICTION:
Dio, per il quale si dispensano e si giudicano tutte le cose.
GOLD:
 Dio, attraverso il quale si amministrano e si giudicano tutte le cose
▶ Generating judgement ...
SCORE: 3

ORIGINAL:
 Unde gli poeti, parlando de lloro, dicono le virtute loro e dicono fabolosamente gli loro difetti, quando alcuna passava l'ordine a lloro deputato
PREDICTION:
Da ciò che dicono i poeti, parlando di sé stessi, raccontano le loro virtù e descrivono in modo straordinario i loro difetti, quando superano i limiti del loro ruolo.
GOLD:
 Perciò i poeti, parlando di loro, dicono le loro virtù e raccontano favolosamente i loro difetti, quando qualcuno superava l'ordine a loro assegnato
▶ Generating judgement ...
SCORE: 4

ORIGINAL:
 e quella cosa, la quale è diricta et onesta, e con virtute, quella sola penso essere lo bene.
PREDICTION:
e quella cosa, la quale è diretta e onesta, e con virtù, penso che sia l'unica cosa buona.
GOLD:
 E quella cosa, che è retta e onesta, e con virtù, quella sola penso essere il bene
▶ Generating judgement ...
SCORE: 3

ORIGINAL:
 Quando li serpenti invellenava di giorno alcuno Romano, allora iera la maraviglia a vedere come li Psille si combattevano al veleno, ché elli imolavano tutto inazzi della loro salive
PREDICTION:
Quando i serpenti si scontravano durante il giorno, era una meraviglia vedere come le vipere combattevano con il loro veleno, poiché si immolavano a vicenda con la loro saliva.
GOLD:
 Quando i serpenti avvelenavano durante il giorno qualche Romano, era una meraviglia vedere come i Psilli si combattevano con il veleno, poiché sacrificavano tutto nel loro stesso veleno
▶ Generating judgement ...
SCORE: 2

ORIGINAL:
 Dice il poeta: oh, che bella cosa è vedere apertamente con gli occhi quando tu glel fai diretro o in culo o in altro
PREDICTION:
Il poeta dice: oh, che bella cosa è vedere chiaramente con gli occhi quando tu glielo fai da dietro o dall'altra parte.
GOLD:
 Afferma il poeta: oh, che cosa bella vedere coi propri occhi quando tu glielo metti dietro o nel sedere o in altro
▶ Generating judgement ...
SCORE: 3

ORIGINAL:
 ma pur questo fu colpa tua, però che volesti cercare di vedere con gli occhi corporali la cosa invisibile.
PREDICTION:
ma fu davvero colpa tua, poiché hai voluto cercare di vedere con gli occhi fisici qualcosa di invisibile.
GOLD:
 Ma anche questa fu colpa tua, perché volevi cercare di vedere con gli occhi materiali ciò che è invisibile.
▶ Generating judgement ...
SCORE: 4

ORIGINAL:
 Vero è, ma non tine rispondo in questo tempo, perciò che ttu se' mio servo, o perciò ch' è tempo feriato, o perciò ch' io non debbo risponderti
PREDICTION:
Veramente, ma non posso risponderti ora, perciò che tu sei mio servo, o perché è un giorno festivo, o perché non dovrei risponderti.
GOLD:
 È vero, ma non ti rispondo in questo momento, perché tu sei mio servo, oppure perché è un giorno festivo, oppure perché non devo rispondert
▶ Generating judgement ...
SCORE: 4

ORIGINAL:
 sì convene che lli desse grande avere perché · lasciasse andare via.
PREDICTION:
sì convenne che gli dessero una grande somma perché lo lasciasse andare via.
GOLD:
 È giusto che gli dessi una grande somma perché se ne andasse
▶ Generating judgement ...
SCORE: 3

ORIGINAL:
 notabile esemplo a ciascuno che si guardasse di fare e di pensar tradigione, il servo, il quale gli avea accusati, fu francato, e fugli donata grande quantità di moneta
PREDICTION:
notevole esempio per chiunque si guardi dal fare e dal pensare di tradire: il servo, che li aveva accusati, fu scagionato e fu donata a lui una grande quantità di denaro.
GOLD:
 Un esempio importante per tutti coloro che vogliano guardarsi dal fare e dal pensare tradimento: il servo che li aveva accusati fu liberato e gli fu donata una grande somma di denaro
▶ Generating judgement ...
SCORE: 3

ORIGINAL:
 che sarebbe a llui cosa sconcia se ll'avesse commesso sì che lla colpa del servo e 'l gastigamento di Platone avesse meritato egualmente.
PREDICTION:
che sarebbe stato sconveniente per lui se l'avesse commessa, così che la colpa del servo e il castigo di Platone avrebbe meritato allo stesso modo.
GOLD:
 Sarebbe per lui cosa vergognosa se l’avesse commessa, tanto che avrebbe meritato sia la colpa del servo sia la punizione di Platone
▶ Generating judgement ...
SCORE: 3

ORIGINAL:
 mostroe massimamente le forze sue, dando lui re a questa cittade ne la quale nacque servo; al quale avvenne lunghissimamente lo imperio tenere
PREDICTION:
mostrò massimamente le sue forze, dando prova di essere re di questa città nella quale nacque servo; ciò che gli riuscì dopo molto tempo, riuscendo a tenere il potere.
GOLD:
 Mostrò soprattutto la sua forza, dandogli il regno di questa città in cui era nato servo; al quale capitò di governare per molto tempo
▶ Generating judgement ...
SCORE: 3

ORIGINAL:
 l' anima muta la sua forza per la propietade di quello corpo a cui ella si congiunge.
PREDICTION:
l'anima cambia la sua forza in base alla proprietà del corpo con cui si unisce.
GOLD:
 L'anima cambia la sua forza in base alle caratteristiche del corpo a cui si unisce
▶ Generating judgement ...
SCORE: 3

ORIGINAL:
 sono due già non in una carne, ma in uno spirito, cioè Iddio, e l' anima. Onde in altro luogo dice S. Paolo: Chi s' accosta a Dio è uno spirito
PREDICTION:

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

Results for /kaggle/input/predicted/predicted_mistral.xlsx (saved to /kaggle/working/predicted_mistral_traduzioni_con_score_semantic.xlsx):
                                            Sentence  \
0  quella guerra ben fatta l' opera perché etc. E...
1  crudele, e di tutte le colpe pigli vendetta, c...
2  Non d' altra forza d' animo fue ornato Ponzio ...
3  Se questo piace a tutti e se 'l tempo hae biso...
4  Officio di questa arte pare che sia dicere app...

                                          prediction  Score
0  Quella guerra fu condotta con grande abilità, ...      3
1  crudele, e di tutte le colpe prendi vendetta, ...      2
2  Non fu ornato di altro coraggio che Ponzio Auf...      2
3  Se questo piace a tutti e se il tempo richiede...      3
4  Sembra che il compito di questa arte sia quell...      3









Judging /kaggle/input/predicted/predicted_opus.csv, semantic


ORIGINAL:
 quella guerra ben fatta l' opera perché etc. Et dall' altra parte Aiaces era uno cavaliere franco e prode all' arme, di gran guisa, ma non era pieno di grande senno
PREDICTION:
che la guerra ha fatto bene perché, ecc. Et, dall'altra parte, Aiaces era un cavaliere che era libero e valoroso alle armi, con grande forza, ma non era pieno di grande senso
GOLD:
 Quella guerra era ben condotta per l’impresa, eccetera. E d’altra parte Aiace era un cavaliere valoroso e audace in battaglia, di grande forza, ma non era dotato di grande saggezza
▶ Generating judgement ...

/usr/local/lib/python3.11/dist-packages/transformers/generation/configuration_utils.py:631: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.7` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/transformers/generation/configuration_utils.py:636: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.8` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/transformers/generation/configuration_utils.py:653: UserWarning: `do_sample` is set to `False`. However, `top_k` is set to `20` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
  warnings.warn(

SCORE: 3

ORIGINAL:
 crudele, e di tutte le colpe pigli vendetta, come dice la legge, ed a neuno cavaliere perdoni che pecchi.
PREDICTION:
crudele, e vendetta per tutti i peccati, come dice la legge, e non perdonare nessun cavaliere per il peccato.
GOLD:
 Crudele, e si vendica di tutte le colpe, come prescrive la legge, e non perdona nessun cavaliere che sbagli
▶ Generating judgement ...
SCORE: 2

ORIGINAL:
 Non d' altra forza d' animo fue ornato Ponzio Aufidiano, romano cavaliere.
PREDICTION:
Ponzio Aufidiano, un cavaliere romano, era adornato senza altra forza della mente.
GOLD:
 Ponzio Aufidiano, cavaliere romano, non fu dotato di minore forza d’animo.
▶ Generating judgement ...
SCORE: 3

ORIGINAL:
 Se questo piace a tutti e se 'l tempo hae bisogno d'avere Pompeio per cavaliere e non per compagno, non riterrò più i fati.
PREDICTION:
Se questo piace a tutti noi e se c'è bisogno di tempo per avere Pompeo come cavaliere e non come compagno, non considererò più i destini.
GOLD:
 Se questa è la volontà comune, e le circostanze richiedono Pompeo come guida piuttosto che come pari, allora non mi opporrò più al destino
▶ Generating judgement ...
SCORE: 3

ORIGINAL:
 Officio di questa arte pare che sia dicere appostatamente per fare credere, fine è far credere per lo dire.
PREDICTION:
L'ufficio di questa arte sembra essere quello di parlare intenzionalmente per far credere a uno, la fine è quello di far credere a uno nel discorso.
GOLD:
 Il compito di quest’arte sembra essere il parlare in modo appropriato per convincere; il suo fine è far credere attraverso il discorso.
▶ Generating judgement ...
SCORE: 3

ORIGINAL:
 Ecco e larghi ventipiovoli caggiono delle risolute nebbie; e potresti credere che tutto il cielo cadesse nel mare
PREDICTION:
Ecco, ci sono grandi tempeste di vento che scorrono dalle nebbie fisse; e voi potete credere che tutti i cieli sono caduti nel mare.
GOLD:
 Ecco, larghi scrosci di pioggia cadono dalle nebbie dissolte; e potresti credere che tutto il cielo stia precipitando nel mare
▶ Generating judgement ...
SCORE: 1

ORIGINAL:
 Però che or chi spererebbe quello che eziandio questi che non vogliono ancora credere in Cristo, già veggiono con noi, e perché nol possono negare, stridono colli denti.
PREDICTION:
Per ora coloro che sperano in ciò che costoro non vogliono ancora credere in Cristo, ora vedono con noi, e perché non possono negarli, strillare i denti.
GOLD:
 Chi potrebbe dunque sperare ciò che anche coloro che ancora non vogliono credere in Cristo già vedono insieme a noi, e poiché non possono negarlo, digrignano i denti?
▶ Generating judgement ...
SCORE: 3

ORIGINAL:
 I vendimenti de' morti et le presure de' vivi fece la frode d'uno feroce re.
PREDICTION:
La vendetta dei morti e l'assicurazione dei vivi hanno reso la frode di un re feroce.
GOLD:
 La frode di un re feroce causò la vendita dei beni dei morti e le pressioni sui vivi.
▶ Generating judgement ...
SCORE: 2

ORIGINAL:
 Acciocché quegli, il quale ora per le sue gran reità è feroce e onorevole, egli d'ogni male afflitto e tormentato della impietà verso il mio padre.
PREDICTION:
perché colui che ora è feroce e onorato per le sue grandi opere, sia tormentato e tormentato da ogni male per l'empietà verso mio padre.
GOLD:
 Affinché colui che ora, per le sue grandi colpe, è feroce e rispettato, sia afflitto e tormentato da ogni male a causa della sua empietà verso mio padre."
▶ Generating judgement ...
SCORE: 2

ORIGINAL:
 Gli uomini spessamente a stare fermi nella bugia incontra la verità.
PREDICTION:
Gli uomini spesso trovano la verità quando sono fermi nelle bugie.
GOLD:
 Gli uomini spesso, rimanendo fermi nella menzogna, incontrano la verità
▶ Generating judgement ...
SCORE: 3

ORIGINAL:
 Marco Cornelio ch'era de' dieci compagni, studiosamente  si riservò di parlare all'ultimo.
PREDICTION:
Marco Cornelio, che era uno dei dieci compagni, ha studiato attentamente per parlare con gli ultimi.
GOLD:
 Marco Cornelio, che faceva parte dei dieci compagni, con attenzione e prudenza si tenne per ultimo nel parlare
▶ Generating judgement ...
SCORE: 3

ORIGINAL:
 cose ch'io sapeva che erano fatte in Italia.
PREDICTION:
le cose che conoscevo sono state fatte in Italia.
GOLD:
 Cose che io sapevo essere state fatte in Italia
▶ Generating judgement ...
SCORE: 3

ORIGINAL:
 Corbio nipote d' Ortensio menò sua vita più bassa e più viziosa
PREDICTION:
Corbio il nipote di Hortensus ha portato la sua vita a inferiore e più vizioso
GOLD:
 Corbio, nipote di Ortensio, condusse una vita più bassa e più viziosa
▶ Generating judgement ...
SCORE: 2

ORIGINAL:
 Altressì uno amante chiamando merzé alla sua donna dice parole e ragioni molte, et ella si difende in suo dire.
PREDICTION:
Eppure un amante, chiamando merito alla sua signora, parla molte parole e ragioni, e lei si difende nel suo discorso.
GOLD:
 Allo stesso modo, un amante chiamando merzé (rimprovero) alla sua donna dice molte parole e ragioni, e lei si difende nel suo discorso
▶ Generating judgement ...
SCORE: 3

ORIGINAL:
 Io mi ricordo (ch. 347) che essendo adirato scapigliai la mia donna. Ohi, quanti dì questa ira mi tolse!
PREDICTION:
Ricordo (cf. 347) che, mentre ero arrabbiato, vagavo per la mia signora. Oh, quanti giorni questa rabbia mi ha portato via!
GOLD:
 Ricordo che, essendo arrabbiato, misi in disordine i capelli della mia donna. Oh, quanti giorni questa collera mi tolse
▶ Generating judgement ...
SCORE: 3

ORIGINAL:
 colui del quale tu tti solevi dolere ch' era amante della tua donna;
PREDICTION:
quella che avevi in lutto per chi era amante della tua donna;
GOLD:
 Colui del quale tu eri solito dolerti perché era amante della tua donna
▶ Generating judgement ...
SCORE: 4

ORIGINAL:
 Ma no sapeano già le nomora di coloro dela congiurazione, ché la donna no nominava già li nomi.
PREDICTION:
Ma non conoscevano già i nomi di coloro che si evocano, perché nessuna donna aveva già chiamato i nomi.
GOLD:
 Ma non conoscevano ancora i nomi di coloro della congiura, perché la donna non aveva ancora nominato i nomi
▶ Generating judgement ...
SCORE: 3

ORIGINAL:
 Creti?  Certo quand'elli si mosse, elli ti dixe: "O fedele mia donna, fa' che in mio luogo ti sia racomandato il nostro hoste troiano".
PREDICTION:
Pensate? Quando egli andò avanti, vi disse: "O mia fedele signora, lasciate che il nostro ostia di Troia sia rimandato a voi al mio posto.
GOLD:
 Creti? Certo, quando lui si mosse, ti disse: 'O mia fedele donna, fa’ che sia raccomandato a te, al mio posto, il nostro ospite troiano
▶ Generating judgement ...
SCORE: 3

ORIGINAL:
 A Milano fue ripressa la malvagità d' una donna in simile bugìa, nel tempo medesimo di questo signore della republica, in questo modo:
PREDICTION:
A Milano, la malvagità di una donna in una tale menzogna è stata repressa, allo stesso tempo di questo signore della repubblica, in questo modo:
GOLD:
 A Milano fu scoperta la malvagità di una donna in una simile menzogna, nel medesimo tempo di questo signore della repubblica, in questo modo
▶ Generating judgement ...
SCORE: 3

ORIGINAL:
 E lamentavansi dell'iniquità d'Appio, e ripiagnevano la malavventurata beltà della pulcella e la necessità del padre.
PREDICTION:
E lamentarono le iniquità di Appio, e lamentarono la malavventura della bellezza del toro e il bisogno di suo padre.
GOLD:
 Si lamentavano dell’ingiustizia di Appio, e piangevano per la sfortunata bellezza della ragazza e per la necessità del padre
▶ Generating judgement ...
SCORE: 2

ORIGINAL:
 Nella quale battaglia, certo io ebbi sempre ardire di ragionare di pace e sempre mi dolfi che non solamente la pace era schifata,
PREDICTION:
In quella battaglia, certamente avevo sempre osato ragionare per la pace, e dormo sempre che non solo era disgustata la pace,
GOLD:
 In quella battaglia, certamente ebbi sempre il coraggio di parlare di pace, e mi dolevo che non solo la pace fosse disprezzata
▶ Generating judgement ...
SCORE: 2

ORIGINAL:
 la seconda suole talora per la grande provedenzia fare timoroso, e la prima per l'ardire rendere altrui matto.
PREDICTION:
il secondo, a volte, è usato dalla grande Provvidenza per fare paura, e il primo, attraverso l'audace, per far impazzire gli altri.
GOLD:
 La seconda talvolta, a causa della grande prudenza, rende timoroso, e la prima , per l’audacia, fa diventare pazzo qualcun altro
▶ Generating judgement ...
SCORE: 3

ORIGINAL:
 Andò nel campo de' Cartaginesi e tutta la legione trasse seco.
PREDICTION:
Entrò nel campo dei Cartaginesi e trasse con sé tutta la legione.
GOLD:
 Entrò nel campo dei Cartaginesi e condusse con sé tutta la legione
▶ Generating judgement ...
SCORE: 3

ORIGINAL:
 Non lo volle cognoscere per nimico. Qesta è quella, la quale diede ardire al profeta Natan a riprendere con grande autoritade quello re, il quale avea peccato.
PREDICTION:
Egli non voleva conoscerlo come un nemico. Questo è ciò che lei, che diede al profeta Natan il coraggio di rimproverare con grande autorità quel re, che aveva peccato.
GOLD:
 Non lo volle riconoscere come nemico. Questa è colei che diede coraggio al profeta Natan a riprendere con grande autorità quel re che aveva peccato
▶ Generating judgement ...
SCORE: 3

ORIGINAL:
 l'armi et insieme con loro passaseno tra li nimici, perçò se alcuno non avesse ardire de questo et sì avevano questo animo.
PREDICTION:
le braccia e, insieme con loro, passarono in mezzo al nemico, perché se qualcuno non avesse osato questo, e così aveva questa mente.
GOLD:
 Le armi e insieme con esse passarono tra i nemici, perciò se qualcuno non avesse avuto coraggio in ciò, non avrebbe avuto questo spirito
▶ Generating judgement ...
SCORE: 2

ORIGINAL:
 Unde ragionevolemente Iob è interpretato dolente;
PREDICTION:
Unde seguendo, Giobbe è interpretato come disgustoso;
GOLD:
 Per questo, ragionevolmente, Giobbe è interpretato come dolente
▶ Generating judgement ...
SCORE: 2

ORIGINAL:
 quello che sopra tutti gli altri perdonasse a' cittadini, e a cui più sicuramente possiate credere; poi ch'egli fu vostro comandatore.
PREDICTION:
colui che, sopra tutti gli altri, ha perdonato i cittadini, e a cui si può sicuramente credere, poiché era il vostro capo.
GOLD:
 Colui che perdonava più di tutti gli altri i cittadini, e a cui potete credere con maggior sicurezza; poiché egli fu vostro comandante
▶ Generating judgement ...
SCORE: 2

ORIGINAL:
 in vano si domanda chi questo Libro scrivesse, con ciò sia cosa che fedelmente si debba credere che l'Auttore di quello fusse lo Spirito santo.
PREDICTION:
Invano, uno si meraviglia chi ha scritto questo Libro, con il quale si deve credere fedelmente che l'Autore di questo è stato lo Spirito Santo.
GOLD:
 Invano si domanda chi abbia scritto questo Libro, poiché si deve credere fedelmente che l’Autore di esso sia lo Spirito Santo.
▶ Generating judgement ...
SCORE: 4

ORIGINAL:
 se non fosse usatissima, ciò parrebbe certo molto più incredibile: certo più agevolmente si può credere quello, posto che l'umano spirito al divino, ed il mutabile allo incommutabile
PREDICTION:
se non fosse usato di più, questo sembrerebbe certamente molto più incredibile: sicuramente si può credere che più facilmente dello spirito umano al divino, e l'immutabile all'immutabile
GOLD:
 Se non fosse così frequentemente usata, questa cosa sembrerebbe certamente molto più incredibile; invece è più facile credere a ciò, dato che lo spirito umano si riferisce a quello divino, e ciò che è mutevole a ciò che è incorruttibile
▶ Generating judgement ...
SCORE: 2

ORIGINAL:
 che prendessero la paga dal camarlingo per loro dispensa et immantenente andassero alla presenzia di messer lo papa per contradiare il passamento de' cavalieri che veniano di Cecilia in Toscana
PREDICTION:
che hanno preso la loro paga dai Camarlingo per la loro dispensa, e immanente, per andare alla presenza del Papa per contraddire il passaggio dei cavalieri che sono venuti da Cecilia in Toscana
GOLD:
 Che prendessero la paga dal camerlingo per la loro dispensa e immediatamente andassero alla presenza di messer il papa per ostacolare il passaggio dei cavalieri che venivano da Cecilia in Toscana.
▶ Generating judgement ...
SCORE: 3

ORIGINAL:
 Teseo reguardò Achelao fortemente meravigliandose e disse così: "O messer Achelao, io vi prego che voi me diciate in che modo voi perdeste
PREDICTION:
Teseo guardò con attenzione Achelaus e disse: "O Messer Achelaus, ti prego di dirmi come hai perso
GOLD:
 Teseo guardò Achelao con grande stupore e disse: 'O messer Achelao, vi prego di dirmi come avete perso
▶ Generating judgement ...
SCORE: 3

ORIGINAL:
 Io spero in messer Iesù di mandare tosto a voi Timoteo, acciocché io sia d'animo buono
PREDICTION:
Spero che Messer Gesù manderà presto Timoteo a voi, affinché io possa essere di buona mente
GOLD:
 Spero in messer Gesù di mandare presto a voi Timoteo, affinché io possa avere buon animo
▶ Generating judgement ...
SCORE: 4

ORIGINAL:
 sanza fallo lo porco salvatico avanza l' uomo d' udire e 'l lupo cerviere del vedere
PREDICTION:
senza successo, il maiale che è salvato avanza l'uomo a sentire e il lupo che è il cervo di vedere
GOLD:
 Senza dubbio il cinghiale selvatico supera l’uomo nell’udito e il lupo nel vedere
▶ Generating judgement ...
SCORE: 1

ORIGINAL:
 uno luogo si mandano lancioni;  la quale cosa i cavalieri l' appellano capo di porco
PREDICTION:
un luogo è mandato da tuoni, quello che i cavalieri chiamano la testa di un maiale
GOLD:
 In un punto si inviano lance; questa manovra i cavalieri la chiamano 'capo di porco'
▶ Generating judgement ...
SCORE: 3

ORIGINAL:
 tenda le reti a li cerbi e sa bene in quali valle dimori il furioso porco cinghiare.
PREDICTION:
tende le reti al cervo, e sa bene in quale valle sta il maiale furioso.
GOLD:
 Tende le reti per i cerbiatti e conosce bene in quali valli dimora il feroce cinghiale
▶ Generating judgement ...
SCORE: 3

ORIGINAL:
 Ora spaventerai li disidirosi cervi con varie e diverse paure, o lo porco cenghiare caggia in terra passato collo spiedo.
PREDICTION:
Ora sarete terrorizzati dal cervo dissidioso con paure diverse e diverse, o il maiale che i cedri cadono per terra, passato, collo di spiedo.
GOLD:
 Ora spaventerai i cervi timorosi con varie e molte paure, o il cinghiale cadrà a terra infilzato dallo spiedo
▶ Generating judgement ...
SCORE: 1

ORIGINAL:
 tratta la natura delle cose incorporali le quali non conversano intra lle corpora, sì come Dio e le divine cose.
PREDICTION:
tratta la natura delle cose che sono incorporate nel corpo; non convergono all'interno del corpo, proprio come Dio e le cose divine fanno.
GOLD:
 Tratta della natura delle cose incorporee, le quali non si trovano entro i corpi, come Dio e le cose divine
▶ Generating judgement ...
SCORE: 3

ORIGINAL:
 Dio, per la quale si dispensano et iudicano tutte le cose.
PREDICTION:
Dio, per mezzo del quale tutte le cose sono dispensate e servite.
GOLD:
 Dio, attraverso il quale si amministrano e si giudicano tutte le cose
▶ Generating judgement ...
SCORE: 4

ORIGINAL:
 Unde gli poeti, parlando de lloro, dicono le virtute loro e dicono fabolosamente gli loro difetti, quando alcuna passava l'ordine a lloro deputato
PREDICTION:
I poeti, quando parlano di loro, parlano delle loro virtù e parlano delle loro colpe, quando alcuni di loro passarono l'ordine al loro vice
GOLD:
 Perciò i poeti, parlando di loro, dicono le loro virtù e raccontano favolosamente i loro difetti, quando qualcuno superava l'ordine a loro assegnato
▶ Generating judgement ...
SCORE: 2

ORIGINAL:
 e quella cosa, la quale è diricta et onesta, e con virtute, quella sola penso essere lo bene.
PREDICTION:
e quella cosa, che è diretta e onesta, e con virtù, quella, credo, è la buona.
GOLD:
 E quella cosa, che è retta e onesta, e con virtù, quella sola penso essere il bene
▶ Generating judgement ...
SCORE: 3

ORIGINAL:
 Quando li serpenti invellenava di giorno alcuno Romano, allora iera la maraviglia a vedere come li Psille si combattevano al veleno, ché elli imolavano tutto inazzi della loro salive
PREDICTION:
Quando i serpenti invasero di giorno alcuni romani, allora si domandarono come i Phillips combattessero contro il veleno, perché era tutta la rabbia dei loro alberelli.
GOLD:
 Quando i serpenti avvelenavano durante il giorno qualche Romano, era una meraviglia vedere come i Psilli si combattevano con il veleno, poiché sacrificavano tutto nel loro stesso veleno
▶ Generating judgement ...
SCORE: 1

ORIGINAL:
 Dice il poeta: oh, che bella cosa è vedere apertamente con gli occhi quando tu glel fai diretro o in culo o in altro
PREDICTION:
Il poeta dice: Oh, che cosa bella è vedere apertamente con gli occhi quando li fai guardare giù sul tuo culo o sul tuo culo
GOLD:
 Afferma il poeta: oh, che cosa bella vedere coi propri occhi quando tu glielo metti dietro o nel sedere o in altro
▶ Generating judgement ...
SCORE: 1

ORIGINAL:
 ma pur questo fu colpa tua, però che volesti cercare di vedere con gli occhi corporali la cosa invisibile.
PREDICTION:
Ma e' stata colpa tua, perche' volevi provare a vedere la cosa invisibile con gli occhi del corpo.
GOLD:
 Ma anche questa fu colpa tua, perché volevi cercare di vedere con gli occhi materiali ciò che è invisibile.
▶ Generating judgement ...
SCORE: 3

ORIGINAL:
 Vero è, ma non tine rispondo in questo tempo, perciò che ttu se' mio servo, o perciò ch' è tempo feriato, o perciò ch' io non debbo risponderti
PREDICTION:
È vero, ma in questo momento non rispondo, perché è per questo che il mio servo è, o perché è ferito, o perché non devo rispondere
GOLD:
 È vero, ma non ti rispondo in questo momento, perché tu sei mio servo, oppure perché è un giorno festivo, oppure perché non devo rispondert
▶ Generating judgement ...
SCORE: 3

ORIGINAL:
 sì convene che lli desse grande avere perché · lasciasse andare via.
PREDICTION:
perché dia loro un grande potere per lasciarli andare.
GOLD:
 È giusto che gli dessi una grande somma perché se ne andasse
▶ Generating judgement ...
SCORE: 3

ORIGINAL:
 notabile esemplo a ciascuno che si guardasse di fare e di pensar tradigione, il servo, il quale gli avea accusati, fu francato, e fugli donata grande quantità di moneta
PREDICTION:
un esempio notevole a ciascuno che guardava se stesso per fare e per pensare tradimento, il servo, che lo aveva accusato, è stato liberato, e gli è stato dato una grande quantità di denaro
GOLD:
 Un esempio importante per tutti coloro che vogliano guardarsi dal fare e dal pensare tradimento: il servo che li aveva accusati fu liberato e gli fu donata una grande somma di denaro
▶ Generating judgement ...
SCORE: 2

ORIGINAL:
 che sarebbe a llui cosa sconcia se ll'avesse commesso sì che lla colpa del servo e 'l gastigamento di Platone avesse meritato egualmente.
PREDICTION:
che sarebbe una cosa sporca per lui se l'avesse commesso in modo che Platos colpa e gastificazione aveva ugualmente meritato.
GOLD:
 Sarebbe per lui cosa vergognosa se l’avesse commessa, tanto che avrebbe meritato sia la colpa del servo sia la punizione di Platone
▶ Generating judgement ...
SCORE: 2

ORIGINAL:
 mostroe massimamente le forze sue, dando lui re a questa cittade ne la quale nacque servo; al quale avvenne lunghissimamente lo imperio tenere
PREDICTION:
Egli mostrò la sua forza in gran parte, dandogli re in questa città in cui nacque servo; a cui l'impero fu tenuto per lungo tempo
GOLD:
 Mostrò soprattutto la sua forza, dandogli il regno di questa città in cui era nato servo; al quale capitò di governare per molto tempo
▶ Generating judgement ...
SCORE: 3

ORIGINAL:
 l' anima muta la sua forza per la propietade di quello corpo a cui ella si congiunge.
PREDICTION:
l'anima cambia la sua forza attraverso il propiziato di quel corpo a cui si unisce.
GOLD:
 L'anima cambia la sua forza in base alle caratteristiche del corpo a cui si unisce
▶ Generating judgement ...
SCORE: 2

ORIGINAL:
 sono due già non in una carne, ma in uno spirito, cioè Iddio, e l' anima. Onde in altro luogo dice S. Paolo: Chi s' accosta a Dio è uno spirito
PREDICTION:

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

Results for /kaggle/input/predicted/predicted_opus.csv (saved to /kaggle/working/predicted_opus_traduzioni_con_score_semantic.xlsx):
                                            Sentence  \
0  quella guerra ben fatta l' opera perché etc. E...
1  crudele, e di tutte le colpe pigli vendetta, c...
2  Non d' altra forza d' animo fue ornato Ponzio ...
3  Se questo piace a tutti e se 'l tempo hae biso...
4  Officio di questa arte pare che sia dicere app...

                                          prediction  Score
0  che la guerra ha fatto bene perché, ecc. Et, d...      3
1  crudele, e vendetta per tutti i peccati, come ...      2
2  Ponzio Aufidiano, un cavaliere romano, era ado...      3
3  Se questo piace a tutti noi e se c'è bisogno d...      3
4  L'ufficio di questa arte sembra essere quello ...      3

# Kappa

In [8]:
from sklearn.metrics import cohen_kappa_score, confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

import numpy as np

In [9]:
idk = {"grammar":"grammatic", "semantic":"semantic"}
for model in ("mistral", "opus"):
    for mode in ("grammar", "semantic"):
        human_df = pd.read_csv(f"/kaggle/input/human-scores-predictionsdd/predicted_{model}_human_score.csv")
        ai_df = pd.read_excel(f"/kaggle/working/predicted_{model}_traduzioni_con_score_{idk[mode]}.xlsx")
        ai_df["human_score"] = human_df["human_"+mode]
        kappa = cohen_kappa_score(human_df["human_"+mode], ai_df["Score"])
        kappa_linear = cohen_kappa_score(human_df["human_"+mode], ai_df["Score"], weights="linear")
        kappa_quadratic = cohen_kappa_score(human_df["human_"+mode], ai_df["Score"], weights="quadratic")
        ai_df['kappa'] = pd.Series(kappa, index=ai_df.index[[0]])
        ai_df['kappa_linear'] = pd.Series(kappa_linear, index=ai_df.index[[0]])
        ai_df['kappa_quadratic'] = pd.Series(kappa_quadratic, index=ai_df.index[[0]])
        ai_df.to_csv(f"/kaggle/working/predicted_{model}_traduzioni_con_score_{idk[mode]}.csv")

In [10]:
ai_df

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,Unnamed: 0,Author,Date,TESTO,Region,MOVIMENTO,Sentence,TRADUZIONE ITALIANA,prediction,Score,...,BERTScore,COMET-22,BLEURT,BLEU,chrF++,TER (inv),human_score,kappa,kappa_linear,kappa_quadratic
0,0,Brunetto Latini,1260-61,Tesoro,fior.,Preumanesimo,quella guerra ben fatta l' opera perché etc. E...,"Quella guerra era ben condotta per l’impresa, ...","che la guerra ha fatto bene perché, ecc. Et, d...",3,...,0.8466,0.6510,0.3861,0.2233,0.4858,0.3625,3,0.098206,0.216478,0.320784
1,1,Bono Giamboni,1292,Il libro de' vizi e delle virtudi,fior.,Preumanesimo,"crudele, e di tutte le colpe pigli vendetta, c...","Crudele, e si vendica di tutte le colpe, come ...","crudele, e vendetta per tutti i peccati, come ...",2,...,0.8049,0.7437,0.4946,NaN,NaN,NaN,5,NaN,NaN,NaN
2,2,Valerio Massimo,1336,Nove libri di fatti e detti memorabili,fior.,Letteratura Enciclopedica Didattica Medievale,Non d' altra forza d' animo fue ornato Ponzio ...,"Ponzio Aufidiano, cavaliere romano, non fu dot...","Ponzio Aufidiano, un cavaliere romano, era ado...",3,...,0.8663,0.6349,0.4154,NaN,NaN,NaN,3,NaN,NaN,NaN
3,3,Luciano,1330/40,Dialoghi (traduzione dal Greco),prat.,Traduzione volgare testo greco,Se questo piace a tutti e se 'l tempo hae biso...,"Se questa è la volontà comune, e le circostanz...",Se questo piace a tutti noi e se c'è bisogno d...,3,...,0.7544,0.6611,0.4573,NaN,NaN,NaN,4,NaN,NaN,NaN
4,4,Brunetto Latini,1260-61,Tesoro,fior.,Preumanesimo,Officio di questa arte pare che sia dicere app...,Il compito di quest’arte sembra essere il parl...,L'ufficio di questa arte sembra essere quello ...,3,...,0.8185,0.6104,0.5894,NaN,NaN,NaN,4,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92,92,Grazia di Meo,1343,NaN,tosc.,letteratura scientifico-morale medievale,"Alchuno è riccho e gentile, ma lamentasi che v...","Qualcuno è ricco e gentile, ma si lamenta perc...","Qualcuno è ricco e gentile, ma si è lamentato ...",3,...,0.8751,0.8742,0.6386,NaN,NaN,NaN,2,NaN,NaN,NaN
93,93,Zanobi da Strada,1361,NaN,tosc.,Letteratura religiosa medievale,"Pietro, essendogli mostrato in figura il popul...","A Pietro, cui fu mostrato in visione il popolo...","Pietro, mostrandogli nella sua figura il popol...",2,...,0.8430,0.6953,0.5983,NaN,NaN,NaN,4,NaN,NaN,NaN
94,94,Declamazioni di Seneca,1392,NaN,tosc.,NaN,pregollo che lo liberasse di quella obbligazio...,Gli chiese di liberarlo da quell’obbligazione ...,"L'ho pregato di liberarlo da quell'obbligo, ne...",2,...,0.8485,0.7417,0.4811,NaN,NaN,NaN,1,NaN,NaN,NaN
95,95,Giovanni da San Miniato,1415,NaN,tosc.,Letteratura religiosa medievale,L'oro verrà dall'Aquilone. Che figuriamo noi p...,L’oro verrà dall’Aquilone . Che cosa rappresen...,L'oro verrà dall'aquilone. Consideriamolo per ...,3,...,0.8469,0.7383,0.6377,NaN,NaN,NaN,2,NaN,NaN,NaN
96,96,Cicerone,1294,Prima Catilinaria (traduzione dal Latino),fior.,NaN,sia in mezzo tra me e te: con noi non puo' tu ...,Sia in mezzo tra me e te: con noi non puoi più...,sia tra voi e me; voi non potete abitare con n...,3,...,0.8074,0.7847,0.7167,NaN,NaN,NaN,4,NaN,NaN,NaN

In [11]:
t = pd.read_csv("/kaggle/working/predicted_mistral_traduzioni_con_score_grammatic.csv")
t

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,Unnamed: 0.1,Unnamed: 0,Author,Date,TESTO,Region,MOVIMENTO,Sentence,TRADUZIONE ITALIANA,prediction,...,BERTScore,COMET-22,BLEURT,BLEU,chrF++,TER (inv),human_score,kappa,kappa_linear,kappa_quadratic
0,0,0,Brunetto Latini,1260-61,Tesoro,fior.,Preumanesimo,quella guerra ben fatta l' opera perché etc. E...,"Quella guerra era ben condotta per l’impresa, ...","Quella guerra fu condotta con grande abilità, ...",...,0.8538,0.7937,0.6002,0.3326,0.5762,0.4737,5,0.019602,0.053996,0.115117
1,1,1,Bono Giamboni,1292,Il libro de' vizi e delle virtudi,fior.,Preumanesimo,"crudele, e di tutte le colpe pigli vendetta, c...","Crudele, e si vendica di tutte le colpe, come ...","crudele, e di tutte le colpe prendi vendetta, ...",...,0.8388,0.7810,0.6234,NaN,NaN,NaN,4,NaN,NaN,NaN
2,2,2,Valerio Massimo,1336,Nove libri di fatti e detti memorabili,fior.,Letteratura Enciclopedica Didattica Medievale,Non d' altra forza d' animo fue ornato Ponzio ...,"Ponzio Aufidiano, cavaliere romano, non fu dot...",Non fu ornato di altro coraggio che Ponzio Auf...,...,0.8476,0.7335,0.4373,NaN,NaN,NaN,3,NaN,NaN,NaN
3,3,3,Luciano,1330/40,Dialoghi (traduzione dal Greco),prat.,Traduzione volgare testo greco,Se questo piace a tutti e se 'l tempo hae biso...,"Se questa è la volontà comune, e le circostanz...",Se questo piace a tutti e se il tempo richiede...,...,0.7887,0.7604,0.5674,NaN,NaN,NaN,5,NaN,NaN,NaN
4,4,4,Brunetto Latini,1260-61,Tesoro,fior.,Preumanesimo,Officio di questa arte pare che sia dicere app...,Il compito di quest’arte sembra essere il parl...,Sembra che il compito di questa arte sia quell...,...,0.8203,0.8577,0.8317,NaN,NaN,NaN,5,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92,92,92,Grazia di Meo,1343,NaN,tosc.,letteratura scientifico-morale medievale,"Alchuno è riccho e gentile, ma lamentasi che v...","Qualcuno è ricco e gentile, ma si lamenta perc...",Non c'è nessuno ricco e gentile che non si lam...,...,0.8389,0.8589,0.7163,NaN,NaN,NaN,4,NaN,NaN,NaN
93,93,93,Zanobi da Strada,1361,NaN,tosc.,Letteratura religiosa medievale,"Pietro, essendogli mostrato in figura il popul...","A Pietro, cui fu mostrato in visione il popolo...","Pietro, una volta mostratogli il popolo pagano...",...,0.8775,0.8289,0.6474,NaN,NaN,NaN,5,NaN,NaN,NaN
94,94,94,Declamazioni di Seneca,1392,NaN,tosc.,NaN,pregollo che lo liberasse di quella obbligazio...,Gli chiese di liberarlo da quell’obbligazione ...,Egli mi pregò di liberarlo da quell'obbligo in...,...,0.8401,0.7996,0.6741,NaN,NaN,NaN,4,NaN,NaN,NaN
95,95,95,Giovanni da San Miniato,1415,NaN,tosc.,Letteratura religiosa medievale,L'oro verrà dall'Aquilone. Che figuriamo noi p...,L’oro verrà dall’Aquilone . Che cosa rappresen...,L'oro proviene da Aquilone. Che noi figuriamo ...,...,0.8878,0.7626,0.5369,NaN,NaN,NaN,4,NaN,NaN,NaN
96,96,96,Cicerone,1294,Prima Catilinaria (traduzione dal Latino),fior.,NaN,sia in mezzo tra me e te: con noi non puo' tu ...,Sia in mezzo tra me e te: con noi non puoi più...,"Tra di noi non puoi più dimorare a lungo, perc...",...,0.9000,0.8907,0.8461,NaN,NaN,NaN,5,NaN,NaN,NaN